<?php
// vim: set expandtab tabstop=4 shiftwidth=4 foldmethod=marker fileencoding=utf-8:
/**
 * Municipios de un departamento
 *
 * PHP version 5
 *
 * @category  SIVeL
 * @package   SIVeL
 * @author    Luca Urech <lucaurech@yahoo.de> y Vladimir Támara  Patiño <vtamara@pasosdeJesus.org>
 * @copyright 2011 Dominio público. Sin garantías.
 * @license   https://www.pasosdejesus.org/dominio_publico_colombia.html Dominio Público. Sin garantías.
 * @version   $$
 * @link      http://sivel.sf.net
 */


require_once "../../aut.php";
require_once $_SESSION['dirsitio'] . "/conf.php";
require_once 'misc.php';

$d = objeto_tabla('municipio');
$db =& $d->getDatabaseConnection();

$municipios = array();
$d->find();
while ($d->fetch()){
    $municipios[$d->id_departamento] = array(
        'id_municipio' => $d->id,
        'name' => $d->nombre
    );
    trigger_error("dep=" . $d->id_departamento . ", mun=" 
        . $d->id . ", nombre=" . $d->nombre);
}
/*// base de datos estatica con municipios
$municipios[0][] = array('id_municipio' => 5, 'name' => 'BRASIL');
$municipios[0][] = array('id_municipio' => 3, 'name' => 'ECUADOR');
$municipios[0][] = array('id_municipio' => 1, 'name' => 'PANAMA');
$municipios[0][] = array('id_municipio' => 4, 'name' => 'PERU');
$municipios[0][] = array('id_municipio' => 2, 'name' => 'VENEZUELA');
$municipios[5][] = array('id_municipio' => 2, 'name' => 'ABEJORRAL');
$municipios[5][] = array('id_municipio' => 4, 'name' => 'ABRIAQUI');
$municipios[5][] = array('id_municipio' => 21, 'name' => 'ALEJANDRIA');
$municipios[5][] = array('id_municipio' => 30, 'name' => 'AMAGA');
$municipios[5][] = array('id_municipio' => 31, 'name' => 'AMALFI');
$municipios[5][] = array('id_municipio' => 34, 'name' => 'ANDES');
$municipios[5][] = array('id_municipio' => 36, 'name' => 'ANGELOPOLIS');
$municipios[5][] = array('id_municipio' => 38, 'name' => 'ANGOSTURA');
$municipios[5][] = array('id_municipio' => 40, 'name' => 'ANORI');
$municipios[5][] = array('id_municipio' => 44, 'name' => 'ANZA');
$municipios[5][] = array('id_municipio' => 45, 'name' => 'APARTADÓ');
$municipios[5][] = array('id_municipio' => 51, 'name' => 'ARBOLETES');
$municipios[5][] = array('id_municipio' => 55, 'name' => 'ARGELIA');
$municipios[5][] = array('id_municipio' => 59, 'name' => 'ARMENIA');
$municipios[5][] = array('id_municipio' => 79, 'name' => 'BARBOSA');
$municipios[5][] = array('id_municipio' => 88, 'name' => 'BELLO');
$municipios[5][] = array('id_municipio' => 86, 'name' => 'BELMIRA');
$municipios[5][] = array('id_municipio' => 91, 'name' => 'BETANIA');
$municipios[5][] = array('id_municipio' => 93, 'name' => 'BETULIA');
$municipios[5][] = array('id_municipio' => 101, 'name' => 'BOLÍVAR');
$municipios[5][] = array('id_municipio' => 107, 'name' => 'BRICEÑO');
$municipios[5][] = array('id_municipio' => 113, 'name' => 'BURITICA');
$municipios[5][] = array('id_municipio' => 120, 'name' => 'CACERES');
$municipios[5][] = array('id_municipio' => 125, 'name' => 'CAICEDO');
$municipios[5][] = array('id_municipio' => 129, 'name' => 'CALDAS');
$municipios[5][] = array('id_municipio' => 134, 'name' => 'CAMPAMENTO');
$municipios[5][] = array('id_municipio' => 138, 'name' => 'CAÑASGORDAS');
$municipios[5][] = array('id_municipio' => 142, 'name' => 'CARACOLI');
$municipios[5][] = array('id_municipio' => 145, 'name' => 'CARAMANTA');
$municipios[5][] = array('id_municipio' => 147, 'name' => 'CAREPA');
$municipios[5][] = array('id_municipio' => 148, 'name' => 'CARMEN DE VIBORAL');
$municipios[5][] = array('id_municipio' => 150, 'name' => 'CAROLINA');
$municipios[5][] = array('id_municipio' => 154, 'name' => 'CAUCASIA');
$municipios[5][] = array('id_municipio' => 172, 'name' => 'CHIGORODÓ');
$municipios[5][] = array('id_municipio' => 190, 'name' => 'CISNEROS');
$municipios[5][] = array('id_municipio' => 197, 'name' => 'COCORNA');
$municipios[5][] = array('id_municipio' => 206, 'name' => 'CONCEPCION');
$municipios[5][] = array('id_municipio' => 209, 'name' => 'CONCORDIA');
$municipios[5][] = array('id_municipio' => 212, 'name' => 'COPACABANA');
$municipios[5][] = array('id_municipio' => 234, 'name' => 'DABEIBA');
$municipios[5][] = array('id_municipio' => 237, 'name' => 'DON MATIAS');
$municipios[5][] = array('id_municipio' => 240, 'name' => 'EBEJICO');
$municipios[5][] = array('id_municipio' => 250, 'name' => 'EL BAGRE');
$municipios[5][] = array('id_municipio' => 264, 'name' => 'ENTRERRIOS');
$municipios[5][] = array('id_municipio' => 266, 'name' => 'ENVIGADO');
$municipios[5][] = array('id_municipio' => 282, 'name' => 'FREDONIA');
$municipios[5][] = array('id_municipio' => 284, 'name' => 'FRONTINO');
$municipios[5][] = array('id_municipio' => 306, 'name' => 'GIRALDO');
$municipios[5][] = array('id_municipio' => 308, 'name' => 'GIRARDOTA');
$municipios[5][] = array('id_municipio' => 310, 'name' => 'GOMEZ PLATA');
$municipios[5][] = array('id_municipio' => 313, 'name' => 'GRANADA');
$municipios[5][] = array('id_municipio' => 315, 'name' => 'GUADALUPE');
$municipios[5][] = array('id_municipio' => 318, 'name' => 'GUARNE');
$municipios[5][] = array('id_municipio' => 321, 'name' => 'GUATAPE');
$municipios[5][] = array('id_municipio' => 347, 'name' => 'HELICONIA');
$municipios[5][] = array('id_municipio' => 353, 'name' => 'HISPANIA');
$municipios[5][] = array('id_municipio' => 360, 'name' => 'ITAGUI');
$municipios[5][] = array('id_municipio' => 361, 'name' => 'ITUANGO');
$municipios[5][] = array('id_municipio' => 364, 'name' => 'JARDIN');
$municipios[5][] = array('id_municipio' => 368, 'name' => 'JERICO');
$municipios[5][] = array('id_municipio' => 376, 'name' => 'LA CEJA');
$municipios[5][] = array('id_municipio' => 380, 'name' => 'LA ESTRELLA');
$municipios[5][] = array('id_municipio' => 390, 'name' => 'LA PINTADA');
$municipios[5][] = array('id_municipio' => 400, 'name' => 'LA UNIÓN');
$municipios[5][] = array('id_municipio' => 411, 'name' => 'LIBORINA');
$municipios[5][] = array('id_municipio' => 425, 'name' => 'MACEO');
$municipios[5][] = array('id_municipio' => 440, 'name' => 'MARINILLA');
$municipios[5][] = array('id_municipio' => 1, 'name' => 'MEDELLÍN');
$municipios[5][] = array('id_municipio' => 467, 'name' => 'MONTEBELLO');
$municipios[5][] = array('id_municipio' => 475, 'name' => 'MURINDÓ');
$municipios[5][] = array('id_municipio' => 480, 'name' => 'MUTATÁ');
$municipios[5][] = array('id_municipio' => 483, 'name' => 'NARIÑO');
$municipios[5][] = array('id_municipio' => 495, 'name' => 'NECHI');
$municipios[5][] = array('id_municipio' => 490, 'name' => 'NECOCLÍ');
$municipios[5][] = array('id_municipio' => 501, 'name' => 'OLAYA');
$municipios[5][] = array('id_municipio' => 541, 'name' => 'PEÑOL');
$municipios[5][] = array('id_municipio' => 543, 'name' => 'PEQUE');
$municipios[5][] = array('id_municipio' => 576, 'name' => 'PUEBLORRICO');
$municipios[5][] = array('id_municipio' => 579, 'name' => 'PUERTO BERRIO');
$municipios[5][] = array('id_municipio' => 585, 'name' => 'PUERTO NARE (LA MAGDALENA)');
$municipios[5][] = array('id_municipio' => 591, 'name' => 'PUERTO TRIUNFO');
$municipios[5][] = array('id_municipio' => 604, 'name' => 'REMEDIOS');
$municipios[5][] = array('id_municipio' => 607, 'name' => 'RETIRO');
$municipios[5][] = array('id_municipio' => 615, 'name' => 'RIONEGRO');
$municipios[5][] = array('id_municipio' => 628, 'name' => 'SABANALARGA');
$municipios[5][] = array('id_municipio' => 631, 'name' => 'SABANETA');
$municipios[5][] = array('id_municipio' => 642, 'name' => 'SALGAR');
$municipios[5][] = array('id_municipio' => 647, 'name' => 'SAN ANDRÉS');
$municipios[5][] = array('id_municipio' => 649, 'name' => 'SAN CARLOS');
$municipios[5][] = array('id_municipio' => 652, 'name' => 'SAN FRANCISCO');
$municipios[5][] = array('id_municipio' => 656, 'name' => 'SAN JERONIMO');
$municipios[5][] = array('id_municipio' => 658, 'name' => 'SAN JOSÉ DE LA MONTAÑA');
$municipios[5][] = array('id_municipio' => 659, 'name' => 'SAN JUAN DE URABÁ');
$municipios[5][] = array('id_municipio' => 660, 'name' => 'SAN LUIS');
$municipios[5][] = array('id_municipio' => 664, 'name' => 'SAN PEDRO');
$municipios[5][] = array('id_municipio' => 665, 'name' => 'SAN PEDRO DE URABÁ');
$municipios[5][] = array('id_municipio' => 667, 'name' => 'SAN RAFAEL');
$municipios[5][] = array('id_municipio' => 670, 'name' => 'SAN ROQUE');
$municipios[5][] = array('id_municipio' => 674, 'name' => 'SAN VICENTE');
$municipios[5][] = array('id_municipio' => 679, 'name' => 'SANTA BARBARA');
$municipios[5][] = array('id_municipio' => 686, 'name' => 'SANTA ROSA DE OSOS');
$municipios[5][] = array('id_municipio' => 42, 'name' => 'SANTAFE DE ANTIOQUIA');
$municipios[5][] = array('id_municipio' => 690, 'name' => 'SANTO DOMINGO');
$municipios[5][] = array('id_municipio' => 697, 'name' => 'SANTUARIO');
$municipios[5][] = array('id_municipio' => 736, 'name' => 'SEGOVIA');
$municipios[5][] = array('id_municipio' => 756, 'name' => 'SONSON');
$municipios[5][] = array('id_municipio' => 761, 'name' => 'SOPETRAN');
$municipios[5][] = array('id_municipio' => 789, 'name' => 'TAMESIS');
$municipios[5][] = array('id_municipio' => 790, 'name' => 'TARAZA');
$municipios[5][] = array('id_municipio' => 792, 'name' => 'TARSO');
$municipios[5][] = array('id_municipio' => 809, 'name' => 'TITIRIBI');
$municipios[5][] = array('id_municipio' => 819, 'name' => 'TOLEDO');
$municipios[5][] = array('id_municipio' => 837, 'name' => 'TURBO');
$municipios[5][] = array('id_municipio' => 842, 'name' => 'URAMITA');
$municipios[5][] = array('id_municipio' => 847, 'name' => 'URRAO');
$municipios[5][] = array('id_municipio' => 854, 'name' => 'VALDIVIA');
$municipios[5][] = array('id_municipio' => 856, 'name' => 'VALPARAISO');
$municipios[5][] = array('id_municipio' => 858, 'name' => 'VEGACHI');
$municipios[5][] = array('id_municipio' => 861, 'name' => 'VENECIA');
$municipios[5][] = array('id_municipio' => 873, 'name' => 'VIGÍA DEL FUERTE');
$municipios[5][] = array('id_municipio' => 885, 'name' => 'YALI');
$municipios[5][] = array('id_municipio' => 887, 'name' => 'YARUMAL');
$municipios[5][] = array('id_municipio' => 890, 'name' => 'YOLOMBO');
$municipios[5][] = array('id_municipio' => 893, 'name' => 'YONDO (CASABE)');
$municipios[5][] = array('id_municipio' => 895, 'name' => 'ZARAGOZA');
$municipios[8][] = array('id_municipio' => 78, 'name' => 'BARANOA');
$municipios[8][] = array('id_municipio' => 1, 'name' => 'BARRANQUILLA');
$municipios[8][] = array('id_municipio' => 137, 'name' => 'CAMPO DE LA CRUZ');
$municipios[8][] = array('id_municipio' => 141, 'name' => 'CANDELARIA');
$municipios[8][] = array('id_municipio' => 296, 'name' => 'GALAPA');
$municipios[8][] = array('id_municipio' => 372, 'name' => 'JUAN DE ACOSTA');
$municipios[8][] = array('id_municipio' => 421, 'name' => 'LURUACO');
$municipios[8][] = array('id_municipio' => 433, 'name' => 'MALAMBO');
$municipios[8][] = array('id_municipio' => 436, 'name' => 'MANATÍ');
$municipios[8][] = array('id_municipio' => 520, 'name' => 'PALMAR DE VARELA');
$municipios[8][] = array('id_municipio' => 549, 'name' => 'PIOJO');
$municipios[8][] = array('id_municipio' => 558, 'name' => 'POLONUEVO');
$municipios[8][] = array('id_municipio' => 560, 'name' => 'PONEDERA');
$municipios[8][] = array('id_municipio' => 573, 'name' => 'PUERTO COLOMBIA');
$municipios[8][] = array('id_municipio' => 606, 'name' => 'REPELON');
$municipios[8][] = array('id_municipio' => 634, 'name' => 'SABANAGRANDE');
$municipios[8][] = array('id_municipio' => 638, 'name' => 'SABANALARGA');
$municipios[8][] = array('id_municipio' => 675, 'name' => 'SANTA LUCIA');
$municipios[8][] = array('id_municipio' => 685, 'name' => 'SANTO TOMAS');
$municipios[8][] = array('id_municipio' => 758, 'name' => 'SOLEDAD');
$municipios[8][] = array('id_municipio' => 770, 'name' => 'SUAN');
$municipios[8][] = array('id_municipio' => 832, 'name' => 'TUBARA');
$municipios[8][] = array('id_municipio' => 849, 'name' => 'USIACURI');
$municipios[11][] = array('id_municipio' => 1, 'name' => 'BOGOTÁ');
$municipios[13][] = array('id_municipio' => 6, 'name' => 'ACHI');
$municipios[13][] = array('id_municipio' => 30, 'name' => 'ALTOS DEL ROSARIO');
$municipios[13][] = array('id_municipio' => 42, 'name' => 'ARENAL');
$municipios[13][] = array('id_municipio' => 52, 'name' => 'ARJONA');
$municipios[13][] = array('id_municipio' => 62, 'name' => 'ARROYOHONDO');
$municipios[13][] = array('id_municipio' => 74, 'name' => 'BARRANCO DE LOBA');
$municipios[13][] = array('id_municipio' => 140, 'name' => 'CALAMAR');
$municipios[13][] = array('id_municipio' => 160, 'name' => 'CANTAGALLO');
$municipios[13][] = array('id_municipio' => 1, 'name' => 'CARTAGENA');
$municipios[13][] = array('id_municipio' => 188, 'name' => 'CICUCO');
$municipios[13][] = array('id_municipio' => 222, 'name' => 'CLEMENCIA');
$municipios[13][] = array('id_municipio' => 212, 'name' => 'CÓRDOBA');
$municipios[13][] = array('id_municipio' => 244, 'name' => 'EL CARMEN DE BOLÍVAR');
$municipios[13][] = array('id_municipio' => 248, 'name' => 'EL GUAMO');
$municipios[13][] = array('id_municipio' => 268, 'name' => 'EL PEÑON');
$municipios[13][] = array('id_municipio' => 300, 'name' => 'HATILLO DE LOBA');
$municipios[13][] = array('id_municipio' => 430, 'name' => 'MAGANGUE');
$municipios[13][] = array('id_municipio' => 433, 'name' => 'MAHATES');
$municipios[13][] = array('id_municipio' => 440, 'name' => 'MARGARITA');
$municipios[13][] = array('id_municipio' => 442, 'name' => 'MARIA LA BAJA');
$municipios[13][] = array('id_municipio' => 468, 'name' => 'MOMPOS');
$municipios[13][] = array('id_municipio' => 458, 'name' => 'MONTECRISTO');
$municipios[13][] = array('id_municipio' => 473, 'name' => 'MORALES');
$municipios[13][] = array('id_municipio' => 549, 'name' => 'PINILLOS');
$municipios[13][] = array('id_municipio' => 580, 'name' => 'REGIDOR');
$municipios[13][] = array('id_municipio' => 600, 'name' => 'RIO VIEJO');
$municipios[13][] = array('id_municipio' => 620, 'name' => 'SAN CRISTOBAL');
$municipios[13][] = array('id_municipio' => 647, 'name' => 'SAN ESTANISLAO');
$municipios[13][] = array('id_municipio' => 650, 'name' => 'SAN FERNANDO');
$municipios[13][] = array('id_municipio' => 654, 'name' => 'SAN JACINTO');
$municipios[13][] = array('id_municipio' => 655, 'name' => 'SAN JACINTO DEL CAUCA');
$municipios[13][] = array('id_municipio' => 657, 'name' => 'SAN JUAN NEPOMUCENO');
$municipios[13][] = array('id_municipio' => 667, 'name' => 'SAN MARTÍN DE LOBA');
$municipios[13][] = array('id_municipio' => 670, 'name' => 'SAN PABLO');
$municipios[13][] = array('id_municipio' => 673, 'name' => 'SANTA CATALINA');
$municipios[13][] = array('id_municipio' => 683, 'name' => 'SANTA ROSA');
$municipios[13][] = array('id_municipio' => 688, 'name' => 'SANTA ROSA DEL SUR');
$municipios[13][] = array('id_municipio' => 744, 'name' => 'SIMITI');
$municipios[13][] = array('id_municipio' => 760, 'name' => 'SOPLAVIENTO');
$municipios[13][] = array('id_municipio' => 780, 'name' => 'TALAIGUA NUEVO');
$municipios[13][] = array('id_municipio' => 810, 'name' => 'TIQUISIO (PUERTO RICO)');
$municipios[13][] = array('id_municipio' => 836, 'name' => 'TURBACO');
$municipios[13][] = array('id_municipio' => 838, 'name' => 'TURBANA');
$municipios[13][] = array('id_municipio' => 873, 'name' => 'VILLANUEVA');
$municipios[13][] = array('id_municipio' => 894, 'name' => 'ZAMBRANO');
$municipios[15][] = array('id_municipio' => 22, 'name' => 'ALMEIDA');
$municipios[15][] = array('id_municipio' => 47, 'name' => 'AQUITANIA');
$municipios[15][] = array('id_municipio' => 51, 'name' => 'ARCABUCO');
$municipios[15][] = array('id_municipio' => 87, 'name' => 'BELEN');
$municipios[15][] = array('id_municipio' => 90, 'name' => 'BERBEO');
$municipios[15][] = array('id_municipio' => 92, 'name' => 'BETEITIVA');
$municipios[15][] = array('id_municipio' => 97, 'name' => 'BOAVITA');
$municipios[15][] = array('id_municipio' => 104, 'name' => 'BOYACA');
$municipios[15][] = array('id_municipio' => 106, 'name' => 'BRICEÑO');
$municipios[15][] = array('id_municipio' => 109, 'name' => 'BUENAVISTA');
$municipios[15][] = array('id_municipio' => 114, 'name' => 'BUSBANZA');
$municipios[15][] = array('id_municipio' => 131, 'name' => 'CALDAS');
$municipios[15][] = array('id_municipio' => 135, 'name' => 'CAMPOHERMOSO');
$municipios[15][] = array('id_municipio' => 162, 'name' => 'CERINZA');
$municipios[15][] = array('id_municipio' => 172, 'name' => 'CHINAVITA');
$municipios[15][] = array('id_municipio' => 176, 'name' => 'CHIQUINQUIRA');
$municipios[15][] = array('id_municipio' => 232, 'name' => 'CHIQUIZA');
$municipios[15][] = array('id_municipio' => 180, 'name' => 'CHISCAS');
$municipios[15][] = array('id_municipio' => 183, 'name' => 'CHITA');
$municipios[15][] = array('id_municipio' => 185, 'name' => 'CHITARAQUE');
$municipios[15][] = array('id_municipio' => 187, 'name' => 'CHIVATA');
$municipios[15][] = array('id_municipio' => 236, 'name' => 'CHIVOR');
$municipios[15][] = array('id_municipio' => 189, 'name' => 'CIENEGA');
$municipios[15][] = array('id_municipio' => 204, 'name' => 'COMBITA');
$municipios[15][] = array('id_municipio' => 212, 'name' => 'COPER');
$municipios[15][] = array('id_municipio' => 215, 'name' => 'CORRALES');
$municipios[15][] = array('id_municipio' => 218, 'name' => 'COVARACHIA');
$municipios[15][] = array('id_municipio' => 223, 'name' => 'CUBARA');
$municipios[15][] = array('id_municipio' => 224, 'name' => 'CUCAITA');
$municipios[15][] = array('id_municipio' => 226, 'name' => 'CUITIVA');
$municipios[15][] = array('id_municipio' => 238, 'name' => 'DUITAMA');
$municipios[15][] = array('id_municipio' => 244, 'name' => 'EL COCUY');
$municipios[15][] = array('id_municipio' => 248, 'name' => 'EL ESPINO');
$municipios[15][] = array('id_municipio' => 272, 'name' => 'FIRAVITOBA');
$municipios[15][] = array('id_municipio' => 276, 'name' => 'FLORESTA');
$municipios[15][] = array('id_municipio' => 293, 'name' => 'GACHANTIVA');
$municipios[15][] = array('id_municipio' => 296, 'name' => 'GAMEZA');
$municipios[15][] = array('id_municipio' => 299, 'name' => 'GARAGOA');
$municipios[15][] = array('id_municipio' => 317, 'name' => 'GUACAMAYAS');
$municipios[15][] = array('id_municipio' => 322, 'name' => 'GUATEQUE');
$municipios[15][] = array('id_municipio' => 325, 'name' => 'GUAYATA');
$municipios[15][] = array('id_municipio' => 332, 'name' => 'GUICAN');
$municipios[15][] = array('id_municipio' => 362, 'name' => 'IZA');
$municipios[15][] = array('id_municipio' => 367, 'name' => 'JENESANO');
$municipios[15][] = array('id_municipio' => 368, 'name' => 'JERICO');
$municipios[15][] = array('id_municipio' => 380, 'name' => 'LA CAPILLA');
$municipios[15][] = array('id_municipio' => 403, 'name' => 'LA UVITA');
$municipios[15][] = array('id_municipio' => 401, 'name' => 'LA VICTORIA');
$municipios[15][] = array('id_municipio' => 377, 'name' => 'LABRANZAGRANDE');
$municipios[15][] = array('id_municipio' => 425, 'name' => 'MACANAL');
$municipios[15][] = array('id_municipio' => 442, 'name' => 'MARIPI');
$municipios[15][] = array('id_municipio' => 455, 'name' => 'MIRAFLORES');
$municipios[15][] = array('id_municipio' => 464, 'name' => 'MONGUA');
$municipios[15][] = array('id_municipio' => 466, 'name' => 'MONGUI');
$municipios[15][] = array('id_municipio' => 469, 'name' => 'MONIQUIRA');
$municipios[15][] = array('id_municipio' => 476, 'name' => 'MOTAVITA');
$municipios[15][] = array('id_municipio' => 480, 'name' => 'MUZO');
$municipios[15][] = array('id_municipio' => 491, 'name' => 'NOBSA');
$municipios[15][] = array('id_municipio' => 494, 'name' => 'NUEVO COLON');
$municipios[15][] = array('id_municipio' => 500, 'name' => 'OICATA');
$municipios[15][] = array('id_municipio' => 507, 'name' => 'OTANCHE');
$municipios[15][] = array('id_municipio' => 511, 'name' => 'PACHAVITA');
$municipios[15][] = array('id_municipio' => 514, 'name' => 'PAEZ');
$municipios[15][] = array('id_municipio' => 516, 'name' => 'PAIPA');
$municipios[15][] = array('id_municipio' => 518, 'name' => 'PAJARITO');
$municipios[15][] = array('id_municipio' => 522, 'name' => 'PANQUEBA');
$municipios[15][] = array('id_municipio' => 531, 'name' => 'PAUNA');
$municipios[15][] = array('id_municipio' => 533, 'name' => 'PAYA');
$municipios[15][] = array('id_municipio' => 537, 'name' => 'PAZ DE RÍO');
$municipios[15][] = array('id_municipio' => 542, 'name' => 'PESCA');
$municipios[15][] = array('id_municipio' => 550, 'name' => 'PISVA');
$municipios[15][] = array('id_municipio' => 572, 'name' => 'PUERTO BOYACA');
$municipios[15][] = array('id_municipio' => 580, 'name' => 'QUIPAMA');
$municipios[15][] = array('id_municipio' => 599, 'name' => 'RAMIRIQUI');
$municipios[15][] = array('id_municipio' => 600, 'name' => 'RAQUIRA');
$municipios[15][] = array('id_municipio' => 621, 'name' => 'RONDON');
$municipios[15][] = array('id_municipio' => 632, 'name' => 'SABOYA');
$municipios[15][] = array('id_municipio' => 638, 'name' => 'SACHICA');
$municipios[15][] = array('id_municipio' => 646, 'name' => 'SAMACA');
$municipios[15][] = array('id_municipio' => 660, 'name' => 'SAN EDUARDO');
$municipios[15][] = array('id_municipio' => 664, 'name' => 'SAN JOSÉ DE PARE');
$municipios[15][] = array('id_municipio' => 667, 'name' => 'SAN LUIS DE GACENO');
$municipios[15][] = array('id_municipio' => 673, 'name' => 'SAN MATEO');
$municipios[15][] = array('id_municipio' => 676, 'name' => 'SAN MIGUEL DE SEMA');
$municipios[15][] = array('id_municipio' => 681, 'name' => 'SAN PABLO DE BORBUR');
$municipios[15][] = array('id_municipio' => 690, 'name' => 'SANTA MARIA');
$municipios[15][] = array('id_municipio' => 693, 'name' => 'SANTA ROSA DE VITERBO');
$municipios[15][] = array('id_municipio' => 696, 'name' => 'SANTA SOFIA');
$municipios[15][] = array('id_municipio' => 686, 'name' => 'SANTANA');
$municipios[15][] = array('id_municipio' => 720, 'name' => 'SATIVANORTE');
$municipios[15][] = array('id_municipio' => 723, 'name' => 'SATIVASUR');
$municipios[15][] = array('id_municipio' => 740, 'name' => 'SIACHOQUE');
$municipios[15][] = array('id_municipio' => 753, 'name' => 'SOATA');
$municipios[15][] = array('id_municipio' => 757, 'name' => 'SOCHA');
$municipios[15][] = array('id_municipio' => 755, 'name' => 'SOCOTA');
$municipios[15][] = array('id_municipio' => 759, 'name' => 'SOGAMOSO');
$municipios[15][] = array('id_municipio' => 761, 'name' => 'SOMONDOCO');
$municipios[15][] = array('id_municipio' => 762, 'name' => 'SORA');
$municipios[15][] = array('id_municipio' => 764, 'name' => 'SORACA');
$municipios[15][] = array('id_municipio' => 763, 'name' => 'SOTAQUIRA');
$municipios[15][] = array('id_municipio' => 774, 'name' => 'SUSACON');
$municipios[15][] = array('id_municipio' => 776, 'name' => 'SUTAMARCHAN');
$municipios[15][] = array('id_municipio' => 778, 'name' => 'SUTATENZA');
$municipios[15][] = array('id_municipio' => 790, 'name' => 'TASCO');
$municipios[15][] = array('id_municipio' => 798, 'name' => 'TENZA');
$municipios[15][] = array('id_municipio' => 804, 'name' => 'TIBANA');
$municipios[15][] = array('id_municipio' => 806, 'name' => 'TIBASOSA');
$municipios[15][] = array('id_municipio' => 808, 'name' => 'TINJACA');
$municipios[15][] = array('id_municipio' => 810, 'name' => 'TIPACOQUE');
$municipios[15][] = array('id_municipio' => 814, 'name' => 'TOCA');
$municipios[15][] = array('id_municipio' => 816, 'name' => 'TOGUI');
$municipios[15][] = array('id_municipio' => 820, 'name' => 'TOPAGA');
$municipios[15][] = array('id_municipio' => 822, 'name' => 'TOTA');
$municipios[15][] = array('id_municipio' => 1, 'name' => 'TUNJA');
$municipios[15][] = array('id_municipio' => 832, 'name' => 'TUNUNGUA');
$municipios[15][] = array('id_municipio' => 835, 'name' => 'TURMEQUE');
$municipios[15][] = array('id_municipio' => 837, 'name' => 'TUTA');
$municipios[15][] = array('id_municipio' => 839, 'name' => 'TUTASA');
$municipios[15][] = array('id_municipio' => 842, 'name' => 'UMBITA');
$municipios[15][] = array('id_municipio' => 861, 'name' => 'VENTAQUEMADA');
$municipios[15][] = array('id_municipio' => 407, 'name' => 'VILLA DE LEYVA');
$municipios[15][] = array('id_municipio' => 879, 'name' => 'VIRACACHA');
$municipios[15][] = array('id_municipio' => 897, 'name' => 'ZETAQUIRA');
$municipios[17][] = array('id_municipio' => 13, 'name' => 'AGUADAS');
$municipios[17][] = array('id_municipio' => 42, 'name' => 'ANSERMA');
$municipios[17][] = array('id_municipio' => 50, 'name' => 'ARANZAZU');
$municipios[17][] = array('id_municipio' => 88, 'name' => 'BELALCAZAR');
$municipios[17][] = array('id_municipio' => 174, 'name' => 'CHINCHINÁ');
$municipios[17][] = array('id_municipio' => 272, 'name' => 'FILADELFIA');
$municipios[17][] = array('id_municipio' => 380, 'name' => 'LA DORADA');
$municipios[17][] = array('id_municipio' => 388, 'name' => 'LA MERCED');
$municipios[17][] = array('id_municipio' => 1, 'name' => 'MANIZALES');
$municipios[17][] = array('id_municipio' => 433, 'name' => 'MANZANARES');
$municipios[17][] = array('id_municipio' => 442, 'name' => 'MARMATO');
$municipios[17][] = array('id_municipio' => 444, 'name' => 'MARQUETALIA');
$municipios[17][] = array('id_municipio' => 446, 'name' => 'MARULANDA');
$municipios[17][] = array('id_municipio' => 486, 'name' => 'NEIRA');
$municipios[17][] = array('id_municipio' => 513, 'name' => 'PACORA');
$municipios[17][] = array('id_municipio' => 524, 'name' => 'PALESTINA');
$municipios[17][] = array('id_municipio' => 541, 'name' => 'PENSILVANIA');
$municipios[17][] = array('id_municipio' => 614, 'name' => 'RIOSUCIO');
$municipios[17][] = array('id_municipio' => 616, 'name' => 'RISARALDA');
$municipios[17][] = array('id_municipio' => 653, 'name' => 'SALAMINA');
$municipios[17][] = array('id_municipio' => 662, 'name' => 'SAMANA');
$municipios[17][] = array('id_municipio' => 665, 'name' => 'SANJOSÉ');
$municipios[17][] = array('id_municipio' => 777, 'name' => 'SUPIA');
$municipios[17][] = array('id_municipio' => 867, 'name' => 'VICTORIA');
$municipios[17][] = array('id_municipio' => 873, 'name' => 'VILLAMARIA');
$municipios[17][] = array('id_municipio' => 877, 'name' => 'VITERBO');
$municipios[18][] = array('id_municipio' => 29, 'name' => 'ALBANIA');
$municipios[18][] = array('id_municipio' => 94, 'name' => 'BELEN DE LOS ANDAQUIES');
$municipios[18][] = array('id_municipio' => 150, 'name' => 'CARTAGENA DEL CHAIRÁ');
$municipios[18][] = array('id_municipio' => 205, 'name' => 'CURILLO');
$municipios[18][] = array('id_municipio' => 247, 'name' => 'EL DONCELLO');
$municipios[18][] = array('id_municipio' => 256, 'name' => 'EL PAUJIL');
$municipios[18][] = array('id_municipio' => 1, 'name' => 'FLORENCIA');
$municipios[18][] = array('id_municipio' => 410, 'name' => 'LA MONTAÑITA');
$municipios[18][] = array('id_municipio' => 460, 'name' => 'MILAN');
$municipios[18][] = array('id_municipio' => 479, 'name' => 'MORELIA');
$municipios[18][] = array('id_municipio' => 592, 'name' => 'PUERTO RICO');
$municipios[18][] = array('id_municipio' => 610, 'name' => 'SAN JOSÉ DEL FRAGUA');
$municipios[18][] = array('id_municipio' => 753, 'name' => 'SAN VICENTE DEL CAGUAN');
$municipios[18][] = array('id_municipio' => 756, 'name' => 'SOLANO');
$municipios[18][] = array('id_municipio' => 785, 'name' => 'SOLITA');
$municipios[18][] = array('id_municipio' => 860, 'name' => 'VALPARAISO');
$municipios[19][] = array('id_municipio' => 22, 'name' => 'ALMAGUER');
$municipios[19][] = array('id_municipio' => 50, 'name' => 'ARGELIA');
$municipios[19][] = array('id_municipio' => 75, 'name' => 'BALBOA');
$municipios[19][] = array('id_municipio' => 100, 'name' => 'BOLÍVAR');
$municipios[19][] = array('id_municipio' => 110, 'name' => 'BUENOS AIRES');
$municipios[19][] = array('id_municipio' => 130, 'name' => 'CAJIBIO');
$municipios[19][] = array('id_municipio' => 137, 'name' => 'CALDONO');
$municipios[19][] = array('id_municipio' => 142, 'name' => 'CALOTO');
$municipios[19][] = array('id_municipio' => 212, 'name' => 'CORINTO');
$municipios[19][] = array('id_municipio' => 256, 'name' => 'EL TAMBO');
$municipios[19][] = array('id_municipio' => 290, 'name' => 'FLORENCIA');
$municipios[19][] = array('id_municipio' => 318, 'name' => 'GUAPI');
$municipios[19][] = array('id_municipio' => 355, 'name' => 'INZA');
$municipios[19][] = array('id_municipio' => 364, 'name' => 'JAMBALO');
$municipios[19][] = array('id_municipio' => 392, 'name' => 'LA SIERRA');
$municipios[19][] = array('id_municipio' => 397, 'name' => 'LA VEGA');
$municipios[19][] = array('id_municipio' => 418, 'name' => 'LOPEZ (MICAY)');
$municipios[19][] = array('id_municipio' => 450, 'name' => 'MERCADERES');
$municipios[19][] = array('id_municipio' => 455, 'name' => 'MIRANDA');
$municipios[19][] = array('id_municipio' => 473, 'name' => 'MORALES');
$municipios[19][] = array('id_municipio' => 513, 'name' => 'PADILLA');
$municipios[19][] = array('id_municipio' => 517, 'name' => 'PAEZ (BELALCAZAR)');
$municipios[19][] = array('id_municipio' => 532, 'name' => 'PATÍA(EL BORDO)');
$municipios[19][] = array('id_municipio' => 533, 'name' => 'PIAMONTE');
$municipios[19][] = array('id_municipio' => 548, 'name' => 'PIENDAMO');
$municipios[19][] = array('id_municipio' => 1, 'name' => 'POPAYÁN');
$municipios[19][] = array('id_municipio' => 573, 'name' => 'PUERTO TEJADA');
$municipios[19][] = array('id_municipio' => 585, 'name' => 'PURACE (COCONUCO)');
$municipios[19][] = array('id_municipio' => 622, 'name' => 'ROSAS');
$municipios[19][] = array('id_municipio' => 693, 'name' => 'SAN SEBASTIAN');
$municipios[19][] = array('id_municipio' => 701, 'name' => 'SANTA ROSA');
$municipios[19][] = array('id_municipio' => 698, 'name' => 'SANTANDER DE QUILICHAO');
$municipios[19][] = array('id_municipio' => 743, 'name' => 'SILVIA');
$municipios[19][] = array('id_municipio' => 760, 'name' => 'SOTARA (PAISPAMBA)');
$municipios[19][] = array('id_municipio' => 780, 'name' => 'SUAREZ');
$municipios[19][] = array('id_municipio' => 785, 'name' => 'SUCRE');
$municipios[19][] = array('id_municipio' => 807, 'name' => 'TIMBIO');
$municipios[19][] = array('id_municipio' => 809, 'name' => 'TIMBIQUI');
$municipios[19][] = array('id_municipio' => 821, 'name' => 'TORIBIO');
$municipios[19][] = array('id_municipio' => 824, 'name' => 'TOTORO');
$municipios[19][] = array('id_municipio' => 845, 'name' => 'VILLA RICA');
$municipios[20][] = array('id_municipio' => 11, 'name' => 'AGUACHICA');
$municipios[20][] = array('id_municipio' => 13, 'name' => 'AGUSTÍN CODAZZI');
$municipios[20][] = array('id_municipio' => 32, 'name' => 'ASTREA');
$municipios[20][] = array('id_municipio' => 45, 'name' => 'BECERRIL');
$municipios[20][] = array('id_municipio' => 60, 'name' => 'BOSCONIA');
$municipios[20][] = array('id_municipio' => 175, 'name' => 'CHIMICHAGUA');
$municipios[20][] = array('id_municipio' => 178, 'name' => 'CHIRIGUANA');
$municipios[20][] = array('id_municipio' => 228, 'name' => 'CURUMANI');
$municipios[20][] = array('id_municipio' => 238, 'name' => 'EL COPEY');
$municipios[20][] = array('id_municipio' => 250, 'name' => 'EL PASO');
$municipios[20][] = array('id_municipio' => 295, 'name' => 'GAMARRA');
$municipios[20][] = array('id_municipio' => 310, 'name' => 'GONZALEZ');
$municipios[20][] = array('id_municipio' => 383, 'name' => 'LA GLORIA');
$municipios[20][] = array('id_municipio' => 400, 'name' => 'LA JAGUA DE IBIRICO');
$municipios[20][] = array('id_municipio' => 621, 'name' => 'LA PAZ (ROBLES)');
$municipios[20][] = array('id_municipio' => 443, 'name' => 'MANAURE BALCON DEL CESAR');
$municipios[20][] = array('id_municipio' => 517, 'name' => 'PAILITAS');
$municipios[20][] = array('id_municipio' => 550, 'name' => 'PELAYA');
$municipios[20][] = array('id_municipio' => 570, 'name' => 'PUEBLO BELLO');
$municipios[20][] = array('id_municipio' => 614, 'name' => 'RIO DE ORO');
$municipios[20][] = array('id_municipio' => 710, 'name' => 'SAN ALBERTO');
$municipios[20][] = array('id_municipio' => 750, 'name' => 'SAN DIEGO');
$municipios[20][] = array('id_municipio' => 770, 'name' => 'SAN MARTÍN');
$municipios[20][] = array('id_municipio' => 787, 'name' => 'TAMALAMEQUE');
$municipios[20][] = array('id_municipio' => 1, 'name' => 'VALLEDUPAR');
$municipios[23][] = array('id_municipio' => 68, 'name' => 'AYAPEL');
$municipios[23][] = array('id_municipio' => 79, 'name' => 'BUENAVISTA');
$municipios[23][] = array('id_municipio' => 90, 'name' => 'CANALETE');
$municipios[23][] = array('id_municipio' => 162, 'name' => 'CERETE');
$municipios[23][] = array('id_municipio' => 168, 'name' => 'CHIMA');
$municipios[23][] = array('id_municipio' => 182, 'name' => 'CHINU');
$municipios[23][] = array('id_municipio' => 189, 'name' => 'CIÉNAGA DE ORO');
$municipios[23][] = array('id_municipio' => 300, 'name' => 'COTORRA');
$municipios[23][] = array('id_municipio' => 350, 'name' => 'LA APARTADA (LA FRONTERA)');
$municipios[23][] = array('id_municipio' => 417, 'name' => 'LORICA');
$municipios[23][] = array('id_municipio' => 419, 'name' => 'LOS CÓRDOBAS');
$municipios[23][] = array('id_municipio' => 464, 'name' => 'MOMIL');
$municipios[23][] = array('id_municipio' => 500, 'name' => 'MOÑITOS');
$municipios[23][] = array('id_municipio' => 466, 'name' => 'MONTELIBANO');
$municipios[23][] = array('id_municipio' => 1, 'name' => 'MONTERÍA');
$municipios[23][] = array('id_municipio' => 555, 'name' => 'PLANETA RICA');
$municipios[23][] = array('id_municipio' => 570, 'name' => 'PUEBLO NUEVO');
$municipios[23][] = array('id_municipio' => 574, 'name' => 'PUERTO ESCONDIDO');
$municipios[23][] = array('id_municipio' => 580, 'name' => 'PUERTO LIBERTADOR');
$municipios[23][] = array('id_municipio' => 586, 'name' => 'PURISIMA');
$municipios[23][] = array('id_municipio' => 660, 'name' => 'SAHAGÚN');
$municipios[23][] = array('id_municipio' => 670, 'name' => 'SAN ANDRÉS SOTAVENTO');
$municipios[23][] = array('id_municipio' => 672, 'name' => 'SAN ANTERO');
$municipios[23][] = array('id_municipio' => 675, 'name' => 'SAN BERNARDO DEL VIENTO');
$municipios[23][] = array('id_municipio' => 678, 'name' => 'SAN CARLOS');
$municipios[23][] = array('id_municipio' => 686, 'name' => 'SAN PELAYO');
$municipios[23][] = array('id_municipio' => 807, 'name' => 'TIERRALTA');
$municipios[23][] = array('id_municipio' => 855, 'name' => 'VALENCIA');
$municipios[25][] = array('id_municipio' => 1, 'name' => 'AGUA DE DIOS');
$municipios[25][] = array('id_municipio' => 19, 'name' => 'ALBAN');
$municipios[25][] = array('id_municipio' => 35, 'name' => 'ANAPOIMA');
$municipios[25][] = array('id_municipio' => 40, 'name' => 'ANOLAIMA');
$municipios[25][] = array('id_municipio' => 53, 'name' => 'ARBELAEZ');
$municipios[25][] = array('id_municipio' => 86, 'name' => 'BELTRAN');
$municipios[25][] = array('id_municipio' => 95, 'name' => 'BITUIMA');
$municipios[25][] = array('id_municipio' => 99, 'name' => 'BOJACA');
$municipios[25][] = array('id_municipio' => 120, 'name' => 'CABRERA');
$municipios[25][] = array('id_municipio' => 123, 'name' => 'CACHIPAY');
$municipios[25][] = array('id_municipio' => 126, 'name' => 'CAJICA');
$municipios[25][] = array('id_municipio' => 148, 'name' => 'CAPARRAPI');
$municipios[25][] = array('id_municipio' => 151, 'name' => 'CAQUEZA');
$municipios[25][] = array('id_municipio' => 154, 'name' => 'CARMEN DE CARUPA');
$municipios[25][] = array('id_municipio' => 168, 'name' => 'CHAGUANI');
$municipios[25][] = array('id_municipio' => 175, 'name' => 'CHIA');
$municipios[25][] = array('id_municipio' => 178, 'name' => 'CHIPAQUE');
$municipios[25][] = array('id_municipio' => 181, 'name' => 'CHOACHI');
$municipios[25][] = array('id_municipio' => 183, 'name' => 'CHOCONTA');
$municipios[25][] = array('id_municipio' => 200, 'name' => 'COGUA');
$municipios[25][] = array('id_municipio' => 214, 'name' => 'COTA');
$municipios[25][] = array('id_municipio' => 224, 'name' => 'CUCUNUBA');
$municipios[25][] = array('id_municipio' => 245, 'name' => 'EL COLEGIO');
$municipios[25][] = array('id_municipio' => 258, 'name' => 'EL PEÑON');
$municipios[25][] = array('id_municipio' => 260, 'name' => 'EL ROSAL');
$municipios[25][] = array('id_municipio' => 269, 'name' => 'FACATATIVA');
$municipios[25][] = array('id_municipio' => 279, 'name' => 'FOMEQUE');
$municipios[25][] = array('id_municipio' => 281, 'name' => 'FOSCA');
$municipios[25][] = array('id_municipio' => 286, 'name' => 'FUNZA');
$municipios[25][] = array('id_municipio' => 288, 'name' => 'FUQUENE');
$municipios[25][] = array('id_municipio' => 290, 'name' => 'FUSAGASUGÁ');
$municipios[25][] = array('id_municipio' => 293, 'name' => 'GACHALA');
$municipios[25][] = array('id_municipio' => 295, 'name' => 'GACHANCIPA');
$municipios[25][] = array('id_municipio' => 297, 'name' => 'GACHETA');
$municipios[25][] = array('id_municipio' => 299, 'name' => 'GAMA');
$municipios[25][] = array('id_municipio' => 307, 'name' => 'GIRARDOT');
$municipios[25][] = array('id_municipio' => 312, 'name' => 'GRANADA');
$municipios[25][] = array('id_municipio' => 317, 'name' => 'GUACHETA');
$municipios[25][] = array('id_municipio' => 320, 'name' => 'GUADUAS');
$municipios[25][] = array('id_municipio' => 322, 'name' => 'GUASCA');
$municipios[25][] = array('id_municipio' => 324, 'name' => 'GUATAQUI');
$municipios[25][] = array('id_municipio' => 326, 'name' => 'GUATAVITA');
$municipios[25][] = array('id_municipio' => 328, 'name' => 'GUAYABAL DE SIQUIMA');
$municipios[25][] = array('id_municipio' => 335, 'name' => 'GUAYABETAL');
$municipios[25][] = array('id_municipio' => 339, 'name' => 'GUTIERREZ');
$municipios[25][] = array('id_municipio' => 368, 'name' => 'JERUSALEN');
$municipios[25][] = array('id_municipio' => 372, 'name' => 'JUNIN');
$municipios[25][] = array('id_municipio' => 377, 'name' => 'LA CALERA');
$municipios[25][] = array('id_municipio' => 386, 'name' => 'LA MESA');
$municipios[25][] = array('id_municipio' => 394, 'name' => 'LA PALMA');
$municipios[25][] = array('id_municipio' => 398, 'name' => 'LA PEÑA');
$municipios[25][] = array('id_municipio' => 402, 'name' => 'LA VEGA');
$municipios[25][] = array('id_municipio' => 407, 'name' => 'LENGUAZAQUE');
$municipios[25][] = array('id_municipio' => 426, 'name' => 'MACHETA');
$municipios[25][] = array('id_municipio' => 430, 'name' => 'MADRID');
$municipios[25][] = array('id_municipio' => 436, 'name' => 'MANTA');
$municipios[25][] = array('id_municipio' => 438, 'name' => 'MEDINA');
$municipios[25][] = array('id_municipio' => 473, 'name' => 'MOSQUERA');
$municipios[25][] = array('id_municipio' => 483, 'name' => 'NARIÑO');
$municipios[25][] = array('id_municipio' => 486, 'name' => 'NEMOCON');
$municipios[25][] = array('id_municipio' => 488, 'name' => 'NILO');
$municipios[25][] = array('id_municipio' => 489, 'name' => 'NIMAIMA');
$municipios[25][] = array('id_municipio' => 491, 'name' => 'NOCAIMA');
$municipios[25][] = array('id_municipio' => 513, 'name' => 'PACHO');
$municipios[25][] = array('id_municipio' => 518, 'name' => 'PAIME');
$municipios[25][] = array('id_municipio' => 524, 'name' => 'PANDI');
$municipios[25][] = array('id_municipio' => 530, 'name' => 'PARATEBUENO');
$municipios[25][] = array('id_municipio' => 535, 'name' => 'PASCA');
$municipios[25][] = array('id_municipio' => 572, 'name' => 'PUERTO SALGAR');
$municipios[25][] = array('id_municipio' => 580, 'name' => 'PULÍ');
$municipios[25][] = array('id_municipio' => 592, 'name' => 'QUEBRADANEGRA');
$municipios[25][] = array('id_municipio' => 594, 'name' => 'QUETAME');
$municipios[25][] = array('id_municipio' => 596, 'name' => 'QUIPILE');
$municipios[25][] = array('id_municipio' => 599, 'name' => 'RAFAEL REYES (APULO)');
$municipios[25][] = array('id_municipio' => 612, 'name' => 'RICAURTE');
$municipios[25][] = array('id_municipio' => 645, 'name' => 'SAN ANTONIO DE TEQUENDAMA');
$municipios[25][] = array('id_municipio' => 649, 'name' => 'SAN BERNARDO');
$municipios[25][] = array('id_municipio' => 653, 'name' => 'SAN CAYETANO');
$municipios[25][] = array('id_municipio' => 658, 'name' => 'SAN FRANCISCO');
$municipios[25][] = array('id_municipio' => 662, 'name' => 'SAN JUAN DE RÍO SECO');
$municipios[25][] = array('id_municipio' => 718, 'name' => 'SASAIMA');
$municipios[25][] = array('id_municipio' => 736, 'name' => 'SESQUILE');
$municipios[25][] = array('id_municipio' => 740, 'name' => 'SIBATÉ');
$municipios[25][] = array('id_municipio' => 743, 'name' => 'SILVANIA');
$municipios[25][] = array('id_municipio' => 745, 'name' => 'SIMIJACA');
$municipios[25][] = array('id_municipio' => 754, 'name' => 'SOACHA');
$municipios[25][] = array('id_municipio' => 758, 'name' => 'SOPO');
$municipios[25][] = array('id_municipio' => 769, 'name' => 'SUBACHOQUE');
$municipios[25][] = array('id_municipio' => 772, 'name' => 'SUESCA');
$municipios[25][] = array('id_municipio' => 777, 'name' => 'SUPATA');
$municipios[25][] = array('id_municipio' => 779, 'name' => 'SUSA');
$municipios[25][] = array('id_municipio' => 781, 'name' => 'SUTATAUSA');
$municipios[25][] = array('id_municipio' => 785, 'name' => 'TABIO');
$municipios[25][] = array('id_municipio' => 793, 'name' => 'TAUSA');
$municipios[25][] = array('id_municipio' => 797, 'name' => 'TENA');
$municipios[25][] = array('id_municipio' => 799, 'name' => 'TENJO');
$municipios[25][] = array('id_municipio' => 805, 'name' => 'TIBACUY');
$municipios[25][] = array('id_municipio' => 807, 'name' => 'TIBIRITA');
$municipios[25][] = array('id_municipio' => 815, 'name' => 'TOCAIMA');
$municipios[25][] = array('id_municipio' => 817, 'name' => 'TOCANCIPA');
$municipios[25][] = array('id_municipio' => 823, 'name' => 'TOPAIPI');
$municipios[25][] = array('id_municipio' => 839, 'name' => 'UBALA');
$municipios[25][] = array('id_municipio' => 841, 'name' => 'UBAQUE');
$municipios[25][] = array('id_municipio' => 843, 'name' => 'UBATE');
$municipios[25][] = array('id_municipio' => 845, 'name' => 'UNE');
$municipios[25][] = array('id_municipio' => 851, 'name' => 'UTICA');
$municipios[25][] = array('id_municipio' => 506, 'name' => 'VENECIA (OSPINA PEREZ)');
$municipios[25][] = array('id_municipio' => 862, 'name' => 'VERGARA');
$municipios[25][] = array('id_municipio' => 867, 'name' => 'VIANI');
$municipios[25][] = array('id_municipio' => 871, 'name' => 'VILLAGOMEZ');
$municipios[25][] = array('id_municipio' => 873, 'name' => 'VILLAPINZON');
$municipios[25][] = array('id_municipio' => 875, 'name' => 'VILLETA');
$municipios[25][] = array('id_municipio' => 878, 'name' => 'VIOTÁ');
$municipios[25][] = array('id_municipio' => 885, 'name' => 'YACOPÍ');
$municipios[25][] = array('id_municipio' => 898, 'name' => 'ZIPACON');
$municipios[25][] = array('id_municipio' => 899, 'name' => 'ZIPAQUIRA');
$municipios[27][] = array('id_municipio' => 6, 'name' => 'ACANDÍ');
$municipios[27][] = array('id_municipio' => 25, 'name' => 'ALTO BAUDO (PIE DE PATO)');
$municipios[27][] = array('id_municipio' => 50, 'name' => 'ATRATO (YUTO)');
$municipios[27][] = array('id_municipio' => 73, 'name' => 'BAGADO');
$municipios[27][] = array('id_municipio' => 75, 'name' => 'BAHIA SOLANO (MUTIS)');
$municipios[27][] = array('id_municipio' => 77, 'name' => 'BAJO BAUDO (PIZARRO)');
$municipios[27][] = array('id_municipio' => 99, 'name' => 'BOJAYÁ (BELLAVISTA)');
$municipios[27][] = array('id_municipio' => 135, 'name' => 'CANTON DEL SAN PABLO');
$municipios[27][] = array('id_municipio' => 150, 'name' => 'CARMEN DEL DARIEN');
$municipios[27][] = array('id_municipio' => 205, 'name' => 'CONDOTO');
$municipios[27][] = array('id_municipio' => 245, 'name' => 'EL CARMEN');
$municipios[27][] = array('id_municipio' => 250, 'name' => 'EL LITORAL DEL SAN JUAN');
$municipios[27][] = array('id_municipio' => 361, 'name' => 'ITSMINA');
$municipios[27][] = array('id_municipio' => 372, 'name' => 'JURADO');
$municipios[27][] = array('id_municipio' => 413, 'name' => 'LLORO');
$municipios[27][] = array('id_municipio' => 425, 'name' => 'MEDIO ATRATO');
$municipios[27][] = array('id_municipio' => 430, 'name' => 'MEDIO BAUDO');
$municipios[27][] = array('id_municipio' => 450, 'name' => 'MEDIO SAN JUAN');
$municipios[27][] = array('id_municipio' => 491, 'name' => 'NOVITA');
$municipios[27][] = array('id_municipio' => 495, 'name' => 'NUQUI');
$municipios[27][] = array('id_municipio' => 1, 'name' => 'QUIBDO');
$municipios[27][] = array('id_municipio' => 600, 'name' => 'RIO QUITO');
$municipios[27][] = array('id_municipio' => 615, 'name' => 'RIOSUCIO');
$municipios[27][] = array('id_municipio' => 660, 'name' => 'SAN JOSÉ DEL PALMAR');
$municipios[27][] = array('id_municipio' => 745, 'name' => 'SIPI');
$municipios[27][] = array('id_municipio' => 787, 'name' => 'TADO');
$municipios[27][] = array('id_municipio' => 800, 'name' => 'UNGUÍA');
$municipios[41][] = array('id_municipio' => 6, 'name' => 'ACEVEDO');
$municipios[41][] = array('id_municipio' => 13, 'name' => 'AGRADO');
$municipios[41][] = array('id_municipio' => 16, 'name' => 'AIPE');
$municipios[41][] = array('id_municipio' => 20, 'name' => 'ALGECIRAS');
$municipios[41][] = array('id_municipio' => 26, 'name' => 'ALTAMIRA');
$municipios[41][] = array('id_municipio' => 78, 'name' => 'BARAYA');
$municipios[41][] = array('id_municipio' => 132, 'name' => 'CAMPOALEGRE');
$municipios[41][] = array('id_municipio' => 206, 'name' => 'COLOMBIA');
$municipios[41][] = array('id_municipio' => 244, 'name' => 'ELIAS');
$municipios[41][] = array('id_municipio' => 298, 'name' => 'GARZON');
$municipios[41][] = array('id_municipio' => 306, 'name' => 'GIGANTE');
$municipios[41][] = array('id_municipio' => 319, 'name' => 'GUADALUPE');
$municipios[41][] = array('id_municipio' => 349, 'name' => 'HOBO');
$municipios[41][] = array('id_municipio' => 357, 'name' => 'IQUIRA');
$municipios[41][] = array('id_municipio' => 359, 'name' => 'ISNOS');
$municipios[41][] = array('id_municipio' => 378, 'name' => 'LA ARGENTINA');
$municipios[41][] = array('id_municipio' => 396, 'name' => 'LA PLATA');
$municipios[41][] = array('id_municipio' => 483, 'name' => 'NATAGA');
$municipios[41][] = array('id_municipio' => 1, 'name' => 'NEIVA');
$municipios[41][] = array('id_municipio' => 503, 'name' => 'OPORAPA');
$municipios[41][] = array('id_municipio' => 518, 'name' => 'PAICOL');
$municipios[41][] = array('id_municipio' => 524, 'name' => 'PALERMO');
$municipios[41][] = array('id_municipio' => 530, 'name' => 'PALESTINA');
$municipios[41][] = array('id_municipio' => 548, 'name' => 'PITAL');
$municipios[41][] = array('id_municipio' => 551, 'name' => 'PITALITO');
$municipios[41][] = array('id_municipio' => 615, 'name' => 'RIVERA');
$municipios[41][] = array('id_municipio' => 660, 'name' => 'SALADOBLANCO');
$municipios[41][] = array('id_municipio' => 668, 'name' => 'SAN AGUSTÍN');
$municipios[41][] = array('id_municipio' => 676, 'name' => 'SANTA MARIA');
$municipios[41][] = array('id_municipio' => 770, 'name' => 'SUAZA');
$municipios[41][] = array('id_municipio' => 791, 'name' => 'TARQUI');
$municipios[41][] = array('id_municipio' => 799, 'name' => 'TELLO');
$municipios[41][] = array('id_municipio' => 801, 'name' => 'TERUEL');
$municipios[41][] = array('id_municipio' => 797, 'name' => 'TESALIA');
$municipios[41][] = array('id_municipio' => 807, 'name' => 'TIMANÁ');
$municipios[41][] = array('id_municipio' => 872, 'name' => 'VILLAVIEJA');
$municipios[41][] = array('id_municipio' => 885, 'name' => 'YAGUARA');
$municipios[44][] = array('id_municipio' => 35, 'name' => 'ALBANIA');
$municipios[44][] = array('id_municipio' => 78, 'name' => 'BARRANCAS');
$municipios[44][] = array('id_municipio' => 90, 'name' => 'DIBULLA');
$municipios[44][] = array('id_municipio' => 98, 'name' => 'DISTRACCION');
$municipios[44][] = array('id_municipio' => 110, 'name' => 'EL MOLINO');
$municipios[44][] = array('id_municipio' => 279, 'name' => 'FONSECA');
$municipios[44][] = array('id_municipio' => 378, 'name' => 'HATONUEVO');
$municipios[44][] = array('id_municipio' => 420, 'name' => 'LA JAGUA DEL PILAR');
$municipios[44][] = array('id_municipio' => 430, 'name' => 'MAICAO');
$municipios[44][] = array('id_municipio' => 560, 'name' => 'MANAURE');
$municipios[44][] = array('id_municipio' => 1, 'name' => 'RIOHACHA');
$municipios[44][] = array('id_municipio' => 650, 'name' => 'SAN JUAN DEL CESAR');
$municipios[44][] = array('id_municipio' => 847, 'name' => 'URIBIA');
$municipios[44][] = array('id_municipio' => 855, 'name' => 'URUMITA');
$municipios[44][] = array('id_municipio' => 874, 'name' => 'VILLANUEVA');
$municipios[47][] = array('id_municipio' => 30, 'name' => 'ALGARROBO');
$municipios[47][] = array('id_municipio' => 53, 'name' => 'ARACATACA');
$municipios[47][] = array('id_municipio' => 58, 'name' => 'ARIGUANI (EL DIFICIL)');
$municipios[47][] = array('id_municipio' => 161, 'name' => 'CERRO SAN ANTONIO');
$municipios[47][] = array('id_municipio' => 170, 'name' => 'CHIVOLO');
$municipios[47][] = array('id_municipio' => 189, 'name' => 'CIÉNAGA');
$municipios[47][] = array('id_municipio' => 205, 'name' => 'CONCORDIA');
$municipios[47][] = array('id_municipio' => 245, 'name' => 'EL BANCO');
$municipios[47][] = array('id_municipio' => 258, 'name' => 'EL PIÑON');
$municipios[47][] = array('id_municipio' => 268, 'name' => 'EL RETEN');
$municipios[47][] = array('id_municipio' => 288, 'name' => 'FUNDACIÓN');
$municipios[47][] = array('id_municipio' => 318, 'name' => 'GUAMAL');
$municipios[47][] = array('id_municipio' => 541, 'name' => 'PEDRAZA');
$municipios[47][] = array('id_municipio' => 545, 'name' => 'PIJIÑO DEL CARMEN');
$municipios[47][] = array('id_municipio' => 551, 'name' => 'PIVIJAY');
$municipios[47][] = array('id_municipio' => 555, 'name' => 'PLATO');
$municipios[47][] = array('id_municipio' => 570, 'name' => 'PUEBLOVIEJO');
$municipios[47][] = array('id_municipio' => 605, 'name' => 'REMOLINO');
$municipios[47][] = array('id_municipio' => 660, 'name' => 'SABANAS DE SAN ANGEL');
$municipios[47][] = array('id_municipio' => 675, 'name' => 'SALAMINA');
$municipios[47][] = array('id_municipio' => 692, 'name' => 'SAN SEBASTIAN DE BUENAVISTA');
$municipios[47][] = array('id_municipio' => 703, 'name' => 'SAN ZENON');
$municipios[47][] = array('id_municipio' => 707, 'name' => 'SANTA ANA');
$municipios[47][] = array('id_municipio' => 720, 'name' => 'SANTA BARBARA DE PINTO');
$municipios[47][] = array('id_municipio' => 1, 'name' => 'SANTA MARTA');
$municipios[47][] = array('id_municipio' => 745, 'name' => 'SITIONUEVO');
$municipios[47][] = array('id_municipio' => 798, 'name' => 'TENERIFE');
$municipios[47][] = array('id_municipio' => 960, 'name' => 'ZAPAYÁN');
$municipios[47][] = array('id_municipio' => 980, 'name' => 'ZONA BANANERA');
$municipios[50][] = array('id_municipio' => 6, 'name' => 'ACACÍAS');
$municipios[50][] = array('id_municipio' => 110, 'name' => 'BARRANCA DE UPIA');
$municipios[50][] = array('id_municipio' => 124, 'name' => 'CABUYARO');
$municipios[50][] = array('id_municipio' => 150, 'name' => 'CASTILLA LA NUEVA');
$municipios[50][] = array('id_municipio' => 223, 'name' => 'CUBARRAL');
$municipios[50][] = array('id_municipio' => 226, 'name' => 'CUMARAL');
$municipios[50][] = array('id_municipio' => 245, 'name' => 'EL CALVARIO');
$municipios[50][] = array('id_municipio' => 251, 'name' => 'EL CASTILLO');
$municipios[50][] = array('id_municipio' => 270, 'name' => 'EL DORADO');
$municipios[50][] = array('id_municipio' => 287, 'name' => 'FUENTE DE ORO');
$municipios[50][] = array('id_municipio' => 313, 'name' => 'GRANADA');
$municipios[50][] = array('id_municipio' => 318, 'name' => 'GUAMAL');
$municipios[50][] = array('id_municipio' => 350, 'name' => 'LA MACARENA');
$municipios[50][] = array('id_municipio' => 370, 'name' => 'LA URIBE');
$municipios[50][] = array('id_municipio' => 400, 'name' => 'LEJANÍAS');
$municipios[50][] = array('id_municipio' => 325, 'name' => 'MAPIRIPÁN');
$municipios[50][] = array('id_municipio' => 330, 'name' => 'MESETAS');
$municipios[50][] = array('id_municipio' => 450, 'name' => 'PUERTO CONCORDIA');
$municipios[50][] = array('id_municipio' => 568, 'name' => 'PUERTO GAITAN');
$municipios[50][] = array('id_municipio' => 577, 'name' => 'PUERTO LLERAS');
$municipios[50][] = array('id_municipio' => 573, 'name' => 'PUERTO LOPEZ');
$municipios[50][] = array('id_municipio' => 590, 'name' => 'PUERTO RICO');
$municipios[50][] = array('id_municipio' => 606, 'name' => 'RESTREPO');
$municipios[50][] = array('id_municipio' => 680, 'name' => 'SAN CARLOS DE GUAROA');
$municipios[50][] = array('id_municipio' => 683, 'name' => 'SAN JUAN DE ARAMA');
$municipios[50][] = array('id_municipio' => 686, 'name' => 'SAN JUANITO');
$municipios[50][] = array('id_municipio' => 689, 'name' => 'SAN MARTÍN');
$municipios[50][] = array('id_municipio' => 1, 'name' => 'VILLAVICENCIO');
$municipios[50][] = array('id_municipio' => 711, 'name' => 'VISTA HERMOSA');
$municipios[52][] = array('id_municipio' => 19, 'name' => 'ALBAN (SAN JOSÉ)');
$municipios[52][] = array('id_municipio' => 22, 'name' => 'ALDANA');
$municipios[52][] = array('id_municipio' => 36, 'name' => 'ANCUYA');
$municipios[52][] = array('id_municipio' => 51, 'name' => 'ARBOLEDA (BERRUECOS)');
$municipios[52][] = array('id_municipio' => 79, 'name' => 'BARBACOAS');
$municipios[52][] = array('id_municipio' => 83, 'name' => 'BELEN');
$municipios[52][] = array('id_municipio' => 110, 'name' => 'BUESACO');
$municipios[52][] = array('id_municipio' => 240, 'name' => 'CHACHAGUI');
$municipios[52][] = array('id_municipio' => 203, 'name' => 'COLON (GENOVA)');
$municipios[52][] = array('id_municipio' => 207, 'name' => 'CONSACA');
$municipios[52][] = array('id_municipio' => 210, 'name' => 'CONTADERO');
$municipios[52][] = array('id_municipio' => 215, 'name' => 'CÓRDOBA');
$municipios[52][] = array('id_municipio' => 224, 'name' => 'CUASPUD (CARLOSAMA)');
$municipios[52][] = array('id_municipio' => 227, 'name' => 'CUMBAL');
$municipios[52][] = array('id_municipio' => 233, 'name' => 'CUMBITARA');
$municipios[52][] = array('id_municipio' => 250, 'name' => 'EL CHARCO');
$municipios[52][] = array('id_municipio' => 254, 'name' => 'EL PEÑOL');
$municipios[52][] = array('id_municipio' => 256, 'name' => 'EL ROSARIO');
$municipios[52][] = array('id_municipio' => 258, 'name' => 'EL TABLON');
$municipios[52][] = array('id_municipio' => 260, 'name' => 'EL TAMBO');
$municipios[52][] = array('id_municipio' => 520, 'name' => 'FRANCISCO PIZARRO');
$municipios[52][] = array('id_municipio' => 287, 'name' => 'FUNES');
$municipios[52][] = array('id_municipio' => 317, 'name' => 'GUACHUCAL');
$municipios[52][] = array('id_municipio' => 320, 'name' => 'GUAITARILLA');
$municipios[52][] = array('id_municipio' => 323, 'name' => 'GUALMATAN');
$municipios[52][] = array('id_municipio' => 352, 'name' => 'ILES');
$municipios[52][] = array('id_municipio' => 354, 'name' => 'IMUES');
$municipios[52][] = array('id_municipio' => 356, 'name' => 'IPIALES');
$municipios[52][] = array('id_municipio' => 378, 'name' => 'LA CRUZ');
$municipios[52][] = array('id_municipio' => 381, 'name' => 'LA FLORIDA');
$municipios[52][] = array('id_municipio' => 385, 'name' => 'LA LLANADA');
$municipios[52][] = array('id_municipio' => 390, 'name' => 'LA TOLA');
$municipios[52][] = array('id_municipio' => 399, 'name' => 'LA UNIÓN');
$municipios[52][] = array('id_municipio' => 405, 'name' => 'LEIVA');
$municipios[52][] = array('id_municipio' => 411, 'name' => 'LINARES');
$municipios[52][] = array('id_municipio' => 418, 'name' => 'LOS ANDES (SOTOMAYOR)');
$municipios[52][] = array('id_municipio' => 427, 'name' => 'MAGUI (PAYAN)');
$municipios[52][] = array('id_municipio' => 435, 'name' => 'MALLAMA (PIEDRANCHA)');
$municipios[52][] = array('id_municipio' => 473, 'name' => 'MOSQUERA');
$municipios[52][] = array('id_municipio' => 480, 'name' => 'NARIÑO');
$municipios[52][] = array('id_municipio' => 490, 'name' => 'OLAYA HERRERA');
$municipios[52][] = array('id_municipio' => 506, 'name' => 'OSPINA');
$municipios[52][] = array('id_municipio' => 1, 'name' => 'PASTO');
$municipios[52][] = array('id_municipio' => 540, 'name' => 'POLICARPA');
$municipios[52][] = array('id_municipio' => 560, 'name' => 'POTOSI');
$municipios[52][] = array('id_municipio' => 565, 'name' => 'PROVIDENCIA');
$municipios[52][] = array('id_municipio' => 573, 'name' => 'PUERRES');
$municipios[52][] = array('id_municipio' => 585, 'name' => 'PUPIALES');
$municipios[52][] = array('id_municipio' => 612, 'name' => 'RICAURTE');
$municipios[52][] = array('id_municipio' => 621, 'name' => 'ROBERTO PAYAN (SAN JOSÉ)');
$municipios[52][] = array('id_municipio' => 678, 'name' => 'SAMANIEGO');
$municipios[52][] = array('id_municipio' => 685, 'name' => 'SAN BERNARDO');
$municipios[52][] = array('id_municipio' => 687, 'name' => 'SAN LORENZO');
$municipios[52][] = array('id_municipio' => 693, 'name' => 'SAN PABLO');
$municipios[52][] = array('id_municipio' => 694, 'name' => 'SAN PEDRO DE CARTAGO');
$municipios[52][] = array('id_municipio' => 683, 'name' => 'SANDONA');
$municipios[52][] = array('id_municipio' => 696, 'name' => 'SANTA BARBARA (ISCUANDE)');
$municipios[52][] = array('id_municipio' => 699, 'name' => 'SANTACRUZ (GUACHAVES)');
$municipios[52][] = array('id_municipio' => 720, 'name' => 'SAPUYES');
$municipios[52][] = array('id_municipio' => 786, 'name' => 'TAMINANGO');
$municipios[52][] = array('id_municipio' => 788, 'name' => 'TANGUA');
$municipios[52][] = array('id_municipio' => 835, 'name' => 'TUMACO');
$municipios[52][] = array('id_municipio' => 838, 'name' => 'TUQUERRES');
$municipios[52][] = array('id_municipio' => 885, 'name' => 'YACUANQUER');
$municipios[54][] = array('id_municipio' => 3, 'name' => 'ABREGO');
$municipios[54][] = array('id_municipio' => 51, 'name' => 'ARBOLEDAS');
$municipios[54][] = array('id_municipio' => 99, 'name' => 'BOCHALEMA');
$municipios[54][] = array('id_municipio' => 109, 'name' => 'BUCARASICA');
$municipios[54][] = array('id_municipio' => 128, 'name' => 'CACHIRA');
$municipios[54][] = array('id_municipio' => 125, 'name' => 'CACOTA');
$municipios[54][] = array('id_municipio' => 172, 'name' => 'CHINACOTA');
$municipios[54][] = array('id_municipio' => 174, 'name' => 'CHITAGA');
$municipios[54][] = array('id_municipio' => 206, 'name' => 'CONVENCIÓN');
$municipios[54][] = array('id_municipio' => 1, 'name' => 'CÚCUTA');
$municipios[54][] = array('id_municipio' => 223, 'name' => 'CUCUTILLA');
$municipios[54][] = array('id_municipio' => 239, 'name' => 'DURANIA');
$municipios[54][] = array('id_municipio' => 245, 'name' => 'EL CARMEN');
$municipios[54][] = array('id_municipio' => 250, 'name' => 'EL TARRA');
$municipios[54][] = array('id_municipio' => 261, 'name' => 'EL ZULIA');
$municipios[54][] = array('id_municipio' => 313, 'name' => 'GRAMALOTE');
$municipios[54][] = array('id_municipio' => 344, 'name' => 'HACARI');
$municipios[54][] = array('id_municipio' => 347, 'name' => 'HERRAN');
$municipios[54][] = array('id_municipio' => 385, 'name' => 'LA ESPERANZA');
$municipios[54][] = array('id_municipio' => 398, 'name' => 'LA PLAYA');
$municipios[54][] = array('id_municipio' => 377, 'name' => 'LABATECA');
$municipios[54][] = array('id_municipio' => 405, 'name' => 'LOS PATIOS');
$municipios[54][] = array('id_municipio' => 418, 'name' => 'LOURDES');
$municipios[54][] = array('id_municipio' => 480, 'name' => 'MUTISCUA');
$municipios[54][] = array('id_municipio' => 498, 'name' => 'OCAÑA');
$municipios[54][] = array('id_municipio' => 518, 'name' => 'PAMPLONA');
$municipios[54][] = array('id_municipio' => 520, 'name' => 'PAMPLONITA');
$municipios[54][] = array('id_municipio' => 553, 'name' => 'PUERTO SANTANDER');
$municipios[54][] = array('id_municipio' => 599, 'name' => 'RAGONVALIA');
$municipios[54][] = array('id_municipio' => 660, 'name' => 'SALAZAR');
$municipios[54][] = array('id_municipio' => 670, 'name' => 'SAN CALIXTO');
$municipios[54][] = array('id_municipio' => 673, 'name' => 'SAN CAYETANO');
$municipios[54][] = array('id_municipio' => 680, 'name' => 'SANTIAGO');
$municipios[54][] = array('id_municipio' => 720, 'name' => 'SARDINATA');
$municipios[54][] = array('id_municipio' => 743, 'name' => 'SILOS');
$municipios[54][] = array('id_municipio' => 800, 'name' => 'TEORAMA');
$municipios[54][] = array('id_municipio' => 810, 'name' => 'TIBU');
$municipios[54][] = array('id_municipio' => 820, 'name' => 'TOLEDO');
$municipios[54][] = array('id_municipio' => 871, 'name' => 'VILLA CARO');
$municipios[54][] = array('id_municipio' => 874, 'name' => 'VILLA DEL ROSARIO');
$municipios[63][] = array('id_municipio' => 1, 'name' => 'ARMENIA');
$municipios[63][] = array('id_municipio' => 111, 'name' => 'BUENAVISTA');
$municipios[63][] = array('id_municipio' => 130, 'name' => 'CALARCA');
$municipios[63][] = array('id_municipio' => 190, 'name' => 'CIRCASIA');
$municipios[63][] = array('id_municipio' => 212, 'name' => 'CÓRDOBA');
$municipios[63][] = array('id_municipio' => 272, 'name' => 'FILANDIA');
$municipios[63][] = array('id_municipio' => 302, 'name' => 'GENOVA');
$municipios[63][] = array('id_municipio' => 401, 'name' => 'LA TEBAIDA');
$municipios[63][] = array('id_municipio' => 470, 'name' => 'MONTENEGRO');
$municipios[63][] = array('id_municipio' => 548, 'name' => 'PIJAO');
$municipios[63][] = array('id_municipio' => 594, 'name' => 'QUIMBAYA');
$municipios[63][] = array('id_municipio' => 690, 'name' => 'SALENTO');
$municipios[66][] = array('id_municipio' => 45, 'name' => 'APIA');
$municipios[66][] = array('id_municipio' => 75, 'name' => 'BALBOA');
$municipios[66][] = array('id_municipio' => 88, 'name' => 'BELEN DE UMBRIA');
$municipios[66][] = array('id_municipio' => 170, 'name' => 'DOS QUEBRADAS');
$municipios[66][] = array('id_municipio' => 318, 'name' => 'GUATICA');
$municipios[66][] = array('id_municipio' => 383, 'name' => 'LA CELIA');
$municipios[66][] = array('id_municipio' => 400, 'name' => 'LA VIRGINIA');
$municipios[66][] = array('id_municipio' => 440, 'name' => 'MARSELLA');
$municipios[66][] = array('id_municipio' => 456, 'name' => 'MISTRATO');
$municipios[66][] = array('id_municipio' => 1, 'name' => 'PEREIRA');
$municipios[66][] = array('id_municipio' => 572, 'name' => 'PUEBLO RICO');
$municipios[66][] = array('id_municipio' => 594, 'name' => 'QUINCHIA');
$municipios[66][] = array('id_municipio' => 682, 'name' => 'SANTA ROSA DE CABAL');
$municipios[66][] = array('id_municipio' => 687, 'name' => 'SANTUARIO');
$municipios[68][] = array('id_municipio' => 13, 'name' => 'AGUADA');
$municipios[68][] = array('id_municipio' => 20, 'name' => 'ALBANIA');
$municipios[68][] = array('id_municipio' => 51, 'name' => 'ARATOCA');
$municipios[68][] = array('id_municipio' => 77, 'name' => 'BARBOSA');
$municipios[68][] = array('id_municipio' => 79, 'name' => 'BARICHARA');
$municipios[68][] = array('id_municipio' => 81, 'name' => 'BARRANCABERMEJA');
$municipios[68][] = array('id_municipio' => 92, 'name' => 'BETULIA');
$municipios[68][] = array('id_municipio' => 101, 'name' => 'BOLÍVAR');
$municipios[68][] = array('id_municipio' => 1, 'name' => 'BUCARAMANGA');
$municipios[68][] = array('id_municipio' => 121, 'name' => 'CABRERA');
$municipios[68][] = array('id_municipio' => 132, 'name' => 'CALIFORNIA');
$municipios[68][] = array('id_municipio' => 147, 'name' => 'CAPITANEJO');
$municipios[68][] = array('id_municipio' => 152, 'name' => 'CARCASI');
$municipios[68][] = array('id_municipio' => 160, 'name' => 'CEPITA');
$municipios[68][] = array('id_municipio' => 162, 'name' => 'CERRITO');
$municipios[68][] = array('id_municipio' => 167, 'name' => 'CHARALA');
$municipios[68][] = array('id_municipio' => 169, 'name' => 'CHARTA');
$municipios[68][] = array('id_municipio' => 176, 'name' => 'CHIMA');
$municipios[68][] = array('id_municipio' => 179, 'name' => 'CHIPATA');
$municipios[68][] = array('id_municipio' => 190, 'name' => 'CIMITARRA');
$municipios[68][] = array('id_municipio' => 207, 'name' => 'CONCEPCION');
$municipios[68][] = array('id_municipio' => 209, 'name' => 'CONFINES');
$municipios[68][] = array('id_municipio' => 211, 'name' => 'CONTRATACION');
$municipios[68][] = array('id_municipio' => 217, 'name' => 'COROMORO');
$municipios[68][] = array('id_municipio' => 229, 'name' => 'CURITI');
$municipios[68][] = array('id_municipio' => 235, 'name' => 'EL CARMEN');
$municipios[68][] = array('id_municipio' => 245, 'name' => 'EL GUACAMAYO');
$municipios[68][] = array('id_municipio' => 250, 'name' => 'EL PEÑON');
$municipios[68][] = array('id_municipio' => 255, 'name' => 'EL PLAYON');
$municipios[68][] = array('id_municipio' => 264, 'name' => 'ENCINO');
$municipios[68][] = array('id_municipio' => 266, 'name' => 'ENCISO');
$municipios[68][] = array('id_municipio' => 271, 'name' => 'FLORIAN');
$municipios[68][] = array('id_municipio' => 276, 'name' => 'FLORIDABLANCA');
$municipios[68][] = array('id_municipio' => 296, 'name' => 'GALAN');
$municipios[68][] = array('id_municipio' => 298, 'name' => 'GAMBITA');
$municipios[68][] = array('id_municipio' => 307, 'name' => 'GIRÓN');
$municipios[68][] = array('id_municipio' => 318, 'name' => 'GUACA');
$municipios[68][] = array('id_municipio' => 320, 'name' => 'GUADALUPE');
$municipios[68][] = array('id_municipio' => 322, 'name' => 'GUAPOTA');
$municipios[68][] = array('id_municipio' => 324, 'name' => 'GUAVATA');
$municipios[68][] = array('id_municipio' => 327, 'name' => 'GUEPSA');
$municipios[68][] = array('id_municipio' => 344, 'name' => 'HATO');
$municipios[68][] = array('id_municipio' => 368, 'name' => 'JESUS MARIA');
$municipios[68][] = array('id_municipio' => 370, 'name' => 'JORDAN');
$municipios[68][] = array('id_municipio' => 377, 'name' => 'LA BELLEZA');
$municipios[68][] = array('id_municipio' => 397, 'name' => 'LA PAZ');
$municipios[68][] = array('id_municipio' => 385, 'name' => 'LANDAZURI');
$municipios[68][] = array('id_municipio' => 406, 'name' => 'LEBRIJA');
$municipios[68][] = array('id_municipio' => 418, 'name' => 'LOS SANTOS');
$municipios[68][] = array('id_municipio' => 425, 'name' => 'MACARAVITA');
$municipios[68][] = array('id_municipio' => 432, 'name' => 'MALAGA');
$municipios[68][] = array('id_municipio' => 444, 'name' => 'MATANZA');
$municipios[68][] = array('id_municipio' => 464, 'name' => 'MOGOTES');
$municipios[68][] = array('id_municipio' => 468, 'name' => 'MOLAGAVITA');
$municipios[68][] = array('id_municipio' => 498, 'name' => 'OCAMONTE');
$municipios[68][] = array('id_municipio' => 500, 'name' => 'OIBA');
$municipios[68][] = array('id_municipio' => 502, 'name' => 'ONZAGA');
$municipios[68][] = array('id_municipio' => 522, 'name' => 'PALMAR');
$municipios[68][] = array('id_municipio' => 524, 'name' => 'PALMAS DEL SOCORRO');
$municipios[68][] = array('id_municipio' => 533, 'name' => 'PARAMO');
$municipios[68][] = array('id_municipio' => 547, 'name' => 'PIEDECUESTA');
$municipios[68][] = array('id_municipio' => 549, 'name' => 'PINCHOTE');
$municipios[68][] = array('id_municipio' => 572, 'name' => 'PUENTE NACIONAL');
$municipios[68][] = array('id_municipio' => 573, 'name' => 'PUERTO PARRA');
$municipios[68][] = array('id_municipio' => 575, 'name' => 'PUERTO WILCHES');
$municipios[68][] = array('id_municipio' => 615, 'name' => 'RIONEGRO');
$municipios[68][] = array('id_municipio' => 655, 'name' => 'SABANA DE TORRES');
$municipios[68][] = array('id_municipio' => 669, 'name' => 'SAN ANDRÉS');
$municipios[68][] = array('id_municipio' => 673, 'name' => 'SAN BENITO');
$municipios[68][] = array('id_municipio' => 679, 'name' => 'SAN GIL');
$municipios[68][] = array('id_municipio' => 682, 'name' => 'SAN JOAQUIN');
$municipios[68][] = array('id_municipio' => 684, 'name' => 'SAN JOSÉ DE MIRANDA');
$municipios[68][] = array('id_municipio' => 686, 'name' => 'SAN MIGUEL');
$municipios[68][] = array('id_municipio' => 689, 'name' => 'SAN VICENTE DE CHUCURI');
$municipios[68][] = array('id_municipio' => 705, 'name' => 'SANTA BARBARA');
$municipios[68][] = array('id_municipio' => 720, 'name' => 'SANTA HELENA DEL OPON');
$municipios[68][] = array('id_municipio' => 745, 'name' => 'SIMACOTA');
$municipios[68][] = array('id_municipio' => 755, 'name' => 'SOCORRO');
$municipios[68][] = array('id_municipio' => 770, 'name' => 'SUAITA');
$municipios[68][] = array('id_municipio' => 773, 'name' => 'SUCRE');
$municipios[68][] = array('id_municipio' => 780, 'name' => 'SURATA');
$municipios[68][] = array('id_municipio' => 820, 'name' => 'TONA');
$municipios[68][] = array('id_municipio' => 855, 'name' => 'VALLE DE SANJOSÉ');
$municipios[68][] = array('id_municipio' => 861, 'name' => 'VELEZ');
$municipios[68][] = array('id_municipio' => 867, 'name' => 'VETAS');
$municipios[68][] = array('id_municipio' => 872, 'name' => 'VILLANUEVA');
$municipios[68][] = array('id_municipio' => 895, 'name' => 'ZAPATOCA');
$municipios[70][] = array('id_municipio' => 110, 'name' => 'BUENAVISTA');
$municipios[70][] = array('id_municipio' => 124, 'name' => 'CAIMITO');
$municipios[70][] = array('id_municipio' => 230, 'name' => 'CHALAN');
$municipios[70][] = array('id_municipio' => 204, 'name' => 'COLOSO (RICAURTE) (RICAURTE)');
$municipios[70][] = array('id_municipio' => 215, 'name' => 'COROZAL');
$municipios[70][] = array('id_municipio' => 221, 'name' => 'COVEÑAS');
$municipios[70][] = array('id_municipio' => 233, 'name' => 'EL ROBLE');
$municipios[70][] = array('id_municipio' => 235, 'name' => 'GALERAS (NUEVA GRANADA)');
$municipios[70][] = array('id_municipio' => 265, 'name' => 'GUARANDA');
$municipios[70][] = array('id_municipio' => 400, 'name' => 'LA UNIÓN');
$municipios[70][] = array('id_municipio' => 418, 'name' => 'LOS PALMITOS');
$municipios[70][] = array('id_municipio' => 429, 'name' => 'MAJAGUAL');
$municipios[70][] = array('id_municipio' => 473, 'name' => 'MORROA');
$municipios[70][] = array('id_municipio' => 508, 'name' => 'OVEJAS');
$municipios[70][] = array('id_municipio' => 523, 'name' => 'PALMITO');
$municipios[70][] = array('id_municipio' => 670, 'name' => 'SAMPUES');
$municipios[70][] = array('id_municipio' => 678, 'name' => 'SAN BENITO ABAD');
$municipios[70][] = array('id_municipio' => 702, 'name' => 'SAN JUAN DE BETULIA');
$municipios[70][] = array('id_municipio' => 708, 'name' => 'SAN MARCOS');
$municipios[70][] = array('id_municipio' => 713, 'name' => 'SAN ONOFRE');
$municipios[70][] = array('id_municipio' => 717, 'name' => 'SAN PEDRO');
$municipios[70][] = array('id_municipio' => 742, 'name' => 'SINCE');
$municipios[70][] = array('id_municipio' => 1, 'name' => 'SINCELEJO');
$municipios[70][] = array('id_municipio' => 771, 'name' => 'SUCRE');
$municipios[70][] = array('id_municipio' => 820, 'name' => 'TOLU');
$municipios[70][] = array('id_municipio' => 823, 'name' => 'TOLUVIEJO');
$municipios[73][] = array('id_municipio' => 24, 'name' => 'ALPUJARRA');
$municipios[73][] = array('id_municipio' => 26, 'name' => 'ALVARADO');
$municipios[73][] = array('id_municipio' => 30, 'name' => 'AMBALEMA');
$municipios[73][] = array('id_municipio' => 43, 'name' => 'ANZOATEGUI');
$municipios[73][] = array('id_municipio' => 55, 'name' => 'ARMERO (GUAYABAL)');
$municipios[73][] = array('id_municipio' => 67, 'name' => 'ATACO');
$municipios[73][] = array('id_municipio' => 124, 'name' => 'CAJAMARCA');
$municipios[73][] = array('id_municipio' => 148, 'name' => 'CARMEN DE APICALA');
$municipios[73][] = array('id_municipio' => 152, 'name' => 'CASABIANCA');
$municipios[73][] = array('id_municipio' => 168, 'name' => 'CHAPARRAL');
$municipios[73][] = array('id_municipio' => 200, 'name' => 'COELLO');
$municipios[73][] = array('id_municipio' => 217, 'name' => 'COYAIMA');
$municipios[73][] = array('id_municipio' => 226, 'name' => 'CUNDAY');
$municipios[73][] = array('id_municipio' => 236, 'name' => 'DOLORES');
$municipios[73][] = array('id_municipio' => 268, 'name' => 'ESPINAL');
$municipios[73][] = array('id_municipio' => 270, 'name' => 'FALAN');
$municipios[73][] = array('id_municipio' => 275, 'name' => 'FLANDES');
$municipios[73][] = array('id_municipio' => 283, 'name' => 'FRESNO');
$municipios[73][] = array('id_municipio' => 319, 'name' => 'GUAMO');
$municipios[73][] = array('id_municipio' => 347, 'name' => 'HERVEO');
$municipios[73][] = array('id_municipio' => 349, 'name' => 'HONDA');
$municipios[73][] = array('id_municipio' => 1, 'name' => 'IBAGUÉ');
$municipios[73][] = array('id_municipio' => 352, 'name' => 'ICONONZO');
$municipios[73][] = array('id_municipio' => 408, 'name' => 'LÉRIDA');
$municipios[73][] = array('id_municipio' => 411, 'name' => 'LIBANO');
$municipios[73][] = array('id_municipio' => 443, 'name' => 'MARIQUITA');
$municipios[73][] = array('id_municipio' => 449, 'name' => 'MELGAR');
$municipios[73][] = array('id_municipio' => 461, 'name' => 'MURILLO');
$municipios[73][] = array('id_municipio' => 483, 'name' => 'NATAGAIMA');
$municipios[73][] = array('id_municipio' => 504, 'name' => 'ORTEGA');
$municipios[73][] = array('id_municipio' => 520, 'name' => 'PALOCABILDO');
$municipios[73][] = array('id_municipio' => 547, 'name' => 'PIEDRAS');
$municipios[73][] = array('id_municipio' => 555, 'name' => 'PLANADAS');
$municipios[73][] = array('id_municipio' => 563, 'name' => 'PRADO');
$municipios[73][] = array('id_municipio' => 585, 'name' => 'PURIFICACIÓN');
$municipios[73][] = array('id_municipio' => 616, 'name' => 'RIOBLANCO');
$municipios[73][] = array('id_municipio' => 622, 'name' => 'RONCESVALLES');
$municipios[73][] = array('id_municipio' => 624, 'name' => 'ROVIRA');
$municipios[73][] = array('id_municipio' => 671, 'name' => 'SALDAÑA');
$municipios[73][] = array('id_municipio' => 675, 'name' => 'SAN ANTONIO');
$municipios[73][] = array('id_municipio' => 678, 'name' => 'SAN LUIS');
$municipios[73][] = array('id_municipio' => 686, 'name' => 'SANTA ISABEL');
$municipios[73][] = array('id_municipio' => 770, 'name' => 'SUAREZ');
$municipios[73][] = array('id_municipio' => 854, 'name' => 'VALLE DE SAN JUAN');
$municipios[73][] = array('id_municipio' => 861, 'name' => 'VENADILLO');
$municipios[73][] = array('id_municipio' => 870, 'name' => 'VILLAHERMOSA');
$municipios[73][] = array('id_municipio' => 873, 'name' => 'VILLARRICA');
$municipios[76][] = array('id_municipio' => 20, 'name' => 'ALCALÁ');
$municipios[76][] = array('id_municipio' => 36, 'name' => 'ANDALUCIA');
$municipios[76][] = array('id_municipio' => 41, 'name' => 'ANSERMANUEVO');
$municipios[76][] = array('id_municipio' => 54, 'name' => 'ARGELIA');
$municipios[76][] = array('id_municipio' => 100, 'name' => 'BOLÍVAR');
$municipios[76][] = array('id_municipio' => 109, 'name' => 'BUENAVENTURA');
$municipios[76][] = array('id_municipio' => 113, 'name' => 'BUGALAGRANDE');
$municipios[76][] = array('id_municipio' => 122, 'name' => 'CAICEDONIA');
$municipios[76][] = array('id_municipio' => 1, 'name' => 'CALI');
$municipios[76][] = array('id_municipio' => 126, 'name' => 'CALIMA (DARIEN)');
$municipios[76][] = array('id_municipio' => 130, 'name' => 'CANDELARIA');
$municipios[76][] = array('id_municipio' => 147, 'name' => 'CARTAGO');
$municipios[76][] = array('id_municipio' => 233, 'name' => 'DAGUA');
$municipios[76][] = array('id_municipio' => 243, 'name' => 'EL AGUILA');
$municipios[76][] = array('id_municipio' => 246, 'name' => 'EL CAIRO');
$municipios[76][] = array('id_municipio' => 248, 'name' => 'EL CERRITO');
$municipios[76][] = array('id_municipio' => 250, 'name' => 'EL DOVIO');
$municipios[76][] = array('id_municipio' => 275, 'name' => 'FLORIDA');
$municipios[76][] = array('id_municipio' => 306, 'name' => 'GINEBRA');
$municipios[76][] = array('id_municipio' => 318, 'name' => 'GUACARI');
$municipios[76][] = array('id_municipio' => 111, 'name' => 'GUADALAJARA DE BUGA');
$municipios[76][] = array('id_municipio' => 364, 'name' => 'JAMUNDI');
$municipios[76][] = array('id_municipio' => 377, 'name' => 'LA CUMBRE');
$municipios[76][] = array('id_municipio' => 400, 'name' => 'LA UNIÓN');
$municipios[76][] = array('id_municipio' => 403, 'name' => 'LA VICTORIA');
$municipios[76][] = array('id_municipio' => 497, 'name' => 'OBANDO');
$municipios[76][] = array('id_municipio' => 520, 'name' => 'PALMIRA');
$municipios[76][] = array('id_municipio' => 563, 'name' => 'PRADERA');
$municipios[76][] = array('id_municipio' => 606, 'name' => 'RESTREPO');
$municipios[76][] = array('id_municipio' => 616, 'name' => 'RIOFRIO');
$municipios[76][] = array('id_municipio' => 622, 'name' => 'ROLDANILLO');
$municipios[76][] = array('id_municipio' => 670, 'name' => 'SAN PEDRO');
$municipios[76][] = array('id_municipio' => 736, 'name' => 'SEVILLA');
$municipios[76][] = array('id_municipio' => 823, 'name' => 'TORO');
$municipios[76][] = array('id_municipio' => 828, 'name' => 'TRUJILLO');
$municipios[76][] = array('id_municipio' => 834, 'name' => 'TULUA');
$municipios[76][] = array('id_municipio' => 845, 'name' => 'ULLOA');
$municipios[76][] = array('id_municipio' => 863, 'name' => 'VERSALLES');
$municipios[76][] = array('id_municipio' => 869, 'name' => 'VIJES');
$municipios[76][] = array('id_municipio' => 890, 'name' => 'YOTOCO');
$municipios[76][] = array('id_municipio' => 892, 'name' => 'YUMBO');
$municipios[76][] = array('id_municipio' => 895, 'name' => 'ZARZAL');
$municipios[81][] = array('id_municipio' => 1, 'name' => 'ARAUCA');
$municipios[81][] = array('id_municipio' => 65, 'name' => 'ARAUQUITA');
$municipios[81][] = array('id_municipio' => 220, 'name' => 'CRAVO NORTE');
$municipios[81][] = array('id_municipio' => 300, 'name' => 'FORTUL');
$municipios[81][] = array('id_municipio' => 591, 'name' => 'PUERTO RONDON');
$municipios[81][] = array('id_municipio' => 736, 'name' => 'SARAVENA');
$municipios[81][] = array('id_municipio' => 794, 'name' => 'TAME');
$municipios[85][] = array('id_municipio' => 10, 'name' => 'AGUAZUL');
$municipios[85][] = array('id_municipio' => 15, 'name' => 'CHAMEZA');
$municipios[85][] = array('id_municipio' => 125, 'name' => 'HATO COROZAL');
$municipios[85][] = array('id_municipio' => 136, 'name' => 'LA SALINA');
$municipios[85][] = array('id_municipio' => 139, 'name' => 'MANI');
$municipios[85][] = array('id_municipio' => 162, 'name' => 'MONTERREY');
$municipios[85][] = array('id_municipio' => 225, 'name' => 'NUNCHIA');
$municipios[85][] = array('id_municipio' => 230, 'name' => 'OROCUE');
$municipios[85][] = array('id_municipio' => 250, 'name' => 'PAZ DE ARIPORO');
$municipios[85][] = array('id_municipio' => 263, 'name' => 'PORE');
$municipios[85][] = array('id_municipio' => 279, 'name' => 'RECETOR');
$municipios[85][] = array('id_municipio' => 300, 'name' => 'SABANALARGA');
$municipios[85][] = array('id_municipio' => 315, 'name' => 'SACAMA');
$municipios[85][] = array('id_municipio' => 325, 'name' => 'SAN LUIS DE PALENQUE');
$municipios[85][] = array('id_municipio' => 400, 'name' => 'TAMARA');
$municipios[85][] = array('id_municipio' => 410, 'name' => 'TAURAMENA');
$municipios[85][] = array('id_municipio' => 430, 'name' => 'TRINIDAD');
$municipios[85][] = array('id_municipio' => 440, 'name' => 'VILLANUEVA');
$municipios[85][] = array('id_municipio' => 1, 'name' => 'YOPAL');
$municipios[86][] = array('id_municipio' => 219, 'name' => 'COLON');
$municipios[86][] = array('id_municipio' => 1, 'name' => 'MOCOA');
$municipios[86][] = array('id_municipio' => 320, 'name' => 'ORITO');
$municipios[86][] = array('id_municipio' => 568, 'name' => 'PUERTO ASIS');
$municipios[86][] = array('id_municipio' => 569, 'name' => 'PUERTO CAICEDO');
$municipios[86][] = array('id_municipio' => 571, 'name' => 'PUERTO GUZMAN');
$municipios[86][] = array('id_municipio' => 573, 'name' => 'PUERTO LEGUIZAMO');
$municipios[86][] = array('id_municipio' => 755, 'name' => 'SAN FRANCISCO');
$municipios[86][] = array('id_municipio' => 757, 'name' => 'SAN MIGUEL');
$municipios[86][] = array('id_municipio' => 760, 'name' => 'SANTIAGO');
$municipios[86][] = array('id_municipio' => 749, 'name' => 'SIBUNDOY');
$municipios[86][] = array('id_municipio' => 865, 'name' => 'VALLE DEL GUAMUEZ (LA HORMIGA)');
$municipios[86][] = array('id_municipio' => 885, 'name' => 'VILLAGARZON');
$municipios[88][] = array('id_municipio' => 564, 'name' => 'PROVIDENCIA');
$municipios[88][] = array('id_municipio' => 1, 'name' => 'SAN ANDRÉS');
$municipios[91][] = array('id_municipio' => 263, 'name' => 'EL ENCANTO');
$municipios[91][] = array('id_municipio' => 405, 'name' => 'LA CHORRERA');
$municipios[91][] = array('id_municipio' => 407, 'name' => 'LA PEDRERA');
$municipios[91][] = array('id_municipio' => 430, 'name' => 'LA VICTORIA');
$municipios[91][] = array('id_municipio' => 1, 'name' => 'LETICIA');
$municipios[91][] = array('id_municipio' => 460, 'name' => 'MIRITI-PARANA');
$municipios[91][] = array('id_municipio' => 669, 'name' => 'PTO SANTANDER');
$municipios[91][] = array('id_municipio' => 530, 'name' => 'PUERTO ALEGRIA');
$municipios[91][] = array('id_municipio' => 536, 'name' => 'PUERTO ARICA');
$municipios[91][] = array('id_municipio' => 540, 'name' => 'PUERTO NARIÑO');
$municipios[91][] = array('id_municipio' => 798, 'name' => 'TARAPACA');
$municipios[94][] = array('id_municipio' => 886, 'name' => 'CACAHUAL');
$municipios[94][] = array('id_municipio' => 343, 'name' => 'GUAVIARE (BARRANCO MINAS)');
$municipios[94][] = array('id_municipio' => 1, 'name' => 'INIRIDA');
$municipios[94][] = array('id_municipio' => 885, 'name' => 'LA GUADALUPE');
$municipios[94][] = array('id_municipio' => 888, 'name' => 'MORICHAL NUEVO');
$municipios[94][] = array('id_municipio' => 887, 'name' => 'PANA PANA');
$municipios[94][] = array('id_municipio' => 884, 'name' => 'PUERTO COLOMBIA');
$municipios[94][] = array('id_municipio' => 883, 'name' => 'SAN FELIPE');
$municipios[95][] = array('id_municipio' => 15, 'name' => 'CALAMAR');
$municipios[95][] = array('id_municipio' => 25, 'name' => 'EL RETORNO');
$municipios[95][] = array('id_municipio' => 200, 'name' => 'MIRAFLORES');
$municipios[95][] = array('id_municipio' => 1, 'name' => 'SAN JOSÉ DEL GUAVIARE');
$municipios[97][] = array('id_municipio' => 161, 'name' => 'CARURU');
$municipios[97][] = array('id_municipio' => 1, 'name' => 'MITU');
$municipios[97][] = array('id_municipio' => 511, 'name' => 'PACOA');
$municipios[97][] = array('id_municipio' => 777, 'name' => 'PAPUNAUA');
$municipios[97][] = array('id_municipio' => 666, 'name' => 'TARAIRA');
$municipios[97][] = array('id_municipio' => 889, 'name' => 'YAVARATE');
$municipios[99][] = array('id_municipio' => 773, 'name' => 'CUMARIBO');
$municipios[99][] = array('id_municipio' => 524, 'name' => 'LA PRIMAVERA');
$municipios[99][] = array('id_municipio' => 1, 'name' => 'PUERTO CARREÑO');
$municipios[99][] = array('id_municipio' => 760, 'name' => 'SAN JOSÉ DE OCUNE');
$municipios[99][] = array('id_municipio' => 624, 'name' => 'SANTA ROSALIA');

*/
$id_departamento = (int)$_GET['id_departamento'];

if ($id_departamento != 0) {
    
    foreach ($municipios[$id_departamento] as $municipio) {
        $municipiosContainer[] = array(
                'id' => (int)$municipio['id_municipio'],
                'name' => utf8_encode($municipio['name'])
            );
    }
    
    echo json_encode($municipiosContainer);
}

?>
